apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.sops.yaml
  - service-postgres.yaml
  - service-mattermost.yaml
  - statefulset-postgres.yaml
  - deployment-mattermost.yaml
  - ingress.yaml
