apiVersion: v1
kind: Secret
metadata:
  name: mattermost-secrets
  namespace: mattermost
  labels:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/component: app
type: Opaque
stringData:
  POSTGRES_PASSWORD: change-me
  MM_SQLSETTINGS_DATASOURCE: postgres://mattermost:change-me@postgres:5432/mattermost?sslmode=disable&connect_timeout=10
