apiVersion: ENC[AES256_GCM,data:J/A=,iv:d5/2+zZ2dU6lZOMCCGbLBQmoGdJs22Ak5kc9l3SXi7I=,tag:UHkbOTlstEzp+GNGIDeZWA==,type:str]
kind: ENC[AES256_GCM,data:L4vtmFnD,iv:3zjObVUdutFrPCymkXQk+sJ0voKt5sDd7+G0Zp6XBug=,tag:S5sTmvfJ4KhBd0ngzhSpfA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QEc80Iqb7YMIudbkLpGWTbrg01n3eA==,iv:JBwiWqz2TczZLa2onTMiLUTqlRHyWWyolH7BQOy/BbU=,tag:4srK0bsSZ95HlHJxXUWWXA==,type:str]
    namespace: ENC[AES256_GCM,data:QzMsMWgoOWc=,iv:FllV4vMdmADhU4ug5Ad7xrsefI4qMEE6hV8l30b0TdA=,tag:TOWTuRhUccc9V3VjlMT1JA==,type:str]
type: ENC[AES256_GCM,data:u8b0Wsp9,iv:h/QfFtPWQFO+969Oq9s3CJ6wFI/fpr7LuZuHcAHvR+0=,tag:EKvkM3YJvIBg+EyUvEjsCA==,type:str]
stringData:
    SLSKD_SLSK_USERNAME: ENC[AES256_GCM,data:4OsYs88tNECQ+YpvC8UfM4La,iv:DKJcFW4xDRzUwtlvof9cya7Bdbf4MpMe9On0JpHGtIM=,tag:mphAREME2gVF8nvbfBaMEg==,type:str]
    SLSKD_SLSK_PASSWORD: ENC[AES256_GCM,data:zTBJB1NfAlcUvVVIzdG30nD5zA3sPqs9kC/5ku6jvb/JGKRyTZU=,iv:aWYo6e58OL7VX0ouBiwJa2GnxmFo7LiHyuZyYwYjK2E=,tag:ZEQ19lmktMuLzy+2DTVqiA==,type:str]
    VPN_USER: ENC[AES256_GCM,data:aQfPdtQ9g2k=,iv:7zkal6nIKt+2PdOvsk05woro+TfU+QaNsdikuOBpPA8=,tag:xNJyvbKDIiVyrYrXWFMEfg==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:eRQoCUciXNcLjQ==,iv:L3HMvU7RR/5HJIDh11NuS0u1H9T44lfoYT8ctDWuWtw=,tag:wqYHSRf/T8qwX/L9S4rqnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYTd0TGkvNzJuRzFJeTkx
            OTVJYjZuQko3Zml0STZZTWF3NEtuZTVXM200CklOSWtRY1VObjlOOFp0SHo4VUJi
            R2V1ejBMY0R5bk5leUNUb2FiNVE3WjAKLS0tIEZYcmtaUFQzMEhYYnZNN2w1UTk5
            NUNIU1pDSTFrZWhHYWJ5SUFESU1DdXMKZtDWNQ1F1Kihl3c/pJTs9ybOl55uZEUO
            UyBUXyLsX1wuUZWzBPQzYoGqcOguZ1EvEWbxlJZ8oBlDeogRMHufEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    lastmodified: "2026-08-04T21:48:52Z"
    mac: ENC[AES256_GCM,data:IhNtRNV/Ujsizd2s1bdclyDF/3Ff8DH3qqCLyKkleoXy2tzix9wf+Bu5TpLMgsopd8rjepkUjO2CHOHTiD+aERnFcNjilHUFjZp7TR2CDZv4NoPohj2lwqYEYcXqJKEsu66Ct1QpETkOaiFHL791ja4dVJHHzpogshWNuqGG7wg=,iv:XVtO+NhmRl0PEvERoDLsVT9s2zTYqdTj7vetHSsF2cU=,tag:GlB/UopohiP7eXBnh4U49w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
