apiVersion: v1
kind: Secret
metadata:
    name: soulsync-vpn-secrets
    namespace: soulsync
type: Opaque
stringData:
    VPN_USER: ENC[AES256_GCM,data:mBmRvppoHOE=,iv:O+meJlGY7ocyVvrQUMywNBxeiXewNVmluFwpdPDqlxc=,tag:hpMF6bELjKgFTxWYyUdfnw==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:13EYvJ+EoXk7AQ==,iv:vHm8NpM5rw1qCtDmJze5xcHABb13lYcYwg/J0f4verQ=,tag:FOTDB8MhAVj0CoOAGqWAFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQmlnL216K09NazR5R09N
            K0xSNkVWUVdPUWFERy8xdzZuTUJzWWdxL3g4CldyemlOdTdHdis0KytpS3hHem5o
            M3NUalhveTl0OVdBVWQ1SWxXVFVRZm8KLS0tIDdoTXpoMUVwQk9zeGVRRk11ZDNq
            bW1nY2hUQXUzekZXd2lENFhhbkNkdEEK6mfDpOg5I0EaASZxn7QbUFBV3WE6GdL/
            8i4FYISiYHRm5L8hiQZ9ijxXen6V/V956+9AwxsNi4LcGYXc2IJJ+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-04T15:23:49Z"
    mac: ENC[AES256_GCM,data:BBQNE5F7sZrY99QZqdMa4ESTnpj1uYtUliRaz98ISB5aOo9eMZ4YxJfrvPFIS/bZcj8Z9SrrhSYOZVu2mCUHD9O+9hoWfcrHzyes18gw4Hg2qnm8H4Byl+4RlasLBokY9DRc6Ch5XV6J/YchUF68b5qrJ6Nlp6uSFghAKmpUJF0=,iv:XPTSB/4UD9OtG05Pd7RETjZGmBMHFc6s6WqX0X0PKKM=,tag:UAr+L0yDbQKNgNjsozxg1g==,type:str]
    version: 3.13.3
