apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
  namespace: freshrss
  labels:
    app.kubernetes.io/name: freshrss
    app.kubernetes.io/component: app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 1Gi
