apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-postgres-data
  namespace: mattermost
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-retain
