apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backups
resources:
  - rbac.yaml
  - configmap.yaml
  - secret.sops.yaml
  - cronjob-pgdump.yaml
  - cronjob-mmctl-export.yaml
