apiVersion: v1
kind: Secret
metadata:
    name: mattermost-backup-secrets
    namespace: backups
type: Opaque
stringData:
    MATTERMOST_POSTGRES_PASSWORD: ENC[AES256_GCM,data:d1vqND5mS803XICrK9DMJlnTRS1P7+I2wZQGXyKgtbY=,iv:AutXiOT/Q0MKVdl4thgBn8OVjxHwYH4z98M1tJCOFOA=,tag:NG5I98Ixh3R3udAeR4xjjA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbERVUzQ1TlF2TWM2OGlB
            eUFzcFRsV1g2SWUyTUpyUmUxNUM5K1Foc2gwClQ1eGJUdUtwdElLRFZiZkZGV0lr
            WDVMK0VDZkErNEVZaWlTY1hQeDViZWcKLS0tIHBZY0hESVhCOE5DNWdXL29tVDRy
            L01oUDYydENrWVJIS2dGNHFZa2s0NUEK3lIxLDYPhIXdF+GFiO6DmA6Mo6xZxL8O
            oj5TwxszgufKRCRo15f5dAHLd+n8DFla0TUYwEZzFkxmbVRNf7diZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T11:35:08Z"
    mac: ENC[AES256_GCM,data:DrgZqfGHT0hWkTWTAH9W1DwnIMA42Wr09bKx9edwk3L33tTXv4bNmSJ8Ri+iUY5IWHDaXHyeBOFdHvph76Fb1aSYmtliL0ikjvSRjrqeUt9pser2ULTllutyxi6WGSM//Ty2SrJ9k2M+K4iqFRsytUCunhdIqleo4RLX8yhm+Ao=,iv:/a3d9Sph4+O0fnFRe1KECXO2JEA8ABOBUsh4Om5gps0=,tag:YCwLQCXQZaiS+E0f+DxRcA==,type:str]
    version: 3.13.0
