apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vaultwarden
    labels:
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/component: app
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:DJMxLSEYU6YPi4oUj//x07CHB2/xrmBKm+jUzhSj/TY=,iv:CTtD7+Rjr1Uh6ntLRIdx5J1m2/ci/rL7vAw8HeQ8voY=,tag:8FCyqxwBJxH/DkymbA8XWA==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcGhhUWdUL2VJQjIrd25R
            UkdPdVRaWnUwN0FvaC9rTUtuK2M0QU02SEdBCjRBeENoTFM4QzJNMTA4MEh1VXd2
            NnBvOUhQMndvUkZWOVdzTG15VkhLSU0KLS0tICt3NnhQQVp4T2hOQkNramwvYmJG
            QVVNTXlzMHBNMjBLbHhGOTZFQkErUGcKxxjLs9GwExWYrPfPtGVTaAYhAmvBaNJk
            icJllqBX4Sw4/6zd5nT3tyGepQX+bHrb91aW5zBZzcAwmmm6JMFLfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T18:07:28Z"
    mac: ENC[AES256_GCM,data:inavC8wWMUR/V8L/bsb/XSOtK3rC6y3CpCmKbNCu8Xco4cw2KE6WCbS3yBt/13njcoVgcqVZCTC5MlZcjXl+2ydgQ8qmpJWw+6yDlaM22pvsUXeEcZjyxpyrPGNAmKHEBgb8lsl/PS3q/Tpz6KSepsopveVnCenuv40V5kDeMf0=,iv:seJJiard5Eo4Vsrubpd9jGzsMrTXlI6YWhjNT/lubrM=,tag:awYNgK8Z/PvuTdIzBQJR0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
