apiVersion: v1
kind: ConfigMap
metadata:
  name: syncthing-config
  namespace: syncthing
  labels:
    app.kubernetes.io/name: syncthing
    app.kubernetes.io/component: app
data:
  TZ: America/New_York
  PUID: "1000"
  PGID: "1000"
  UMASK: "002"
  STGUIADDRESS: 127.0.0.1:8384

