apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helm-values-configmap.yaml
  - helmrelease.yaml
  - servicemonitor-longhorn.yaml
  - podmonitor-traefik.yaml
configMapGenerator:
  - name: grafana-dashboard-kubernetes-cluster-overview
    namespace: observability
    files:
      - dashboards/kubernetes-cluster-overview.json
    options:
      labels:
        grafana_dashboard: "1"
      annotations:
        grafana_folder: Kubernetes
generatorOptions:
  disableNameSuffixHash: true
