apiVersion: v1
kind: Secret
metadata:
    name: observability-core-secret-values
    namespace: observability
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:AjZ6KHKrTrctvanzAlyuMRENtIHkTS+HphSZLQRcytp8QHEd7BzmQiK6VVdggjPDym0mkAX4DolShmaOWl3kWVEflGoRD0NpE2UobOGr0o77pZLMBHIXhFQT/2Vsind66HQgLmVapuMxec5CkEPhHKDnSGULxzUovK6YWianonVpSvyxnlLzOAo5phVbWTfZJOAol6y0IQFjy8dVdtiO/V5VbrBWG7w1x8y1+28SvPkvxYXW90ooopsb1wBRd13Mz2A7jrpiaPoQpUc16iZio9eTMp4+uwpUs+x03EQxDi+PwdzfrzixKSCih6JFKxMmh5QhdFVnXiZuDX7LJNZfMIfvVoIqGTF9gWhltlBnsckgdSiN73DXAvNiBJBQ66i+zEO5nDl8Xswnx1uge7Ah4Sn/qAGFnXUlGCFP6flfJTqAnio4uu2KU/jlt4Lb9qVU/2Bjam+OiTiSTysQjcImFXUecWalb3kmL/fgvi3bIfVv9l1Db5Wmcalq/rtGFCCk1/92eGUUkTAgL13KmZa6nEJF2Ee6x5CkU3LH+7KSuIRfHF4oCok8F5oyb85e3WhwKartm9uTMr71TDu0J+hRsXhYdMclnOPlBoAIb7Wt9zZviHqMt6/lSLAmnUwtZ+nDdkl1NW/x8d3dHFrP3jH0Ozr7thZ/pAZG9V3dinxvOykv1LREgF4tt1IwrZov3GXvhIcOFTBa2eYo86urtl1zMVc9dXpXOsVSIWVB/HbqLZmTcrc0zPpuWGxPwiv+ph3VJriC1pNpXykG08CYbrxkq3tv47LGSZupPjzbIJuCjHY1gFwAQe7wudIzkSlir0brJM74Bha0,iv:vur4y5uznPqnnb9977bgG8bPhOsVBn/i/aIh7Rk97XQ=,tag:KnZ/3Ab10gwCP7ealJ3eVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNanRQVHh6Y2kveGJ1QWtt
            cFNWd2lqb085S2dJTW5KUS9UUDFCUmFGd20wCkdUU0Q4a3RtVnA1bkdndFhhZTZP
            RVUyWHp0Z0tvZVZYU1dINUY2SmZRQTQKLS0tIFlEeUh1UGFUdE9KTjRRajRncDI5
            N082ZUhVcFFBWVdwT1M2a01MM3BqcGsKbnZNxeyBbtX0/I5ShilwkXgWMVdfjxiJ
            tp3g3EIF33wEaNrVXm4szRqj2lAS94gnTTwyI74AkCNxzPxkpxZJmQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T17:40:49Z"
    mac: ENC[AES256_GCM,data:1K2PmvVDV86DbHzwlF5F0xHVNmT9vDeKjn8TAQ3bT39OWgboR0a6nOdyu/Wx1j18qxgKiP7TYprPIkF7AyWKaFUJUBQf5kERynPFX0+z5FbFD8YUqz9Obia7Ji6+uk2t3Y9Tw8LA7RGkC80qUzW3VlZ7T01C2J69/ZLVGPd45JQ=,iv:nZfCZ4iLpsf3JWVFPf+ZOy4VA+InYI5RajFe6UwEWAI=,tag:oeFmFwSNHTCU9rM5jWXWjA==,type:str]
    version: 3.13.1
