apiVersion: v1
kind: Secret
metadata:
    name: observability-core-secret-values
    namespace: observability
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:JKSa0HbVb9rXCUhe43E2TVGiiDoWKN+nbqWdr3q1qbU+gmno81iKYD56TeoB8S3F/q0gxzUpYeqScQ==,iv:CCPVxK2apLJr/z9NKSOBwOvmoizTGPyD1rstHId5vls=,tag:WnLyMT/xOa95ZdvyKfyNCg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArLzcrL08yQXdVWjQwMVNO
            cW5vMHA5T0FLQVluUWlQSGJqNlBPMlF3eWcwCnNmNXlhTFN4bEhOc1JJSi9VWWF6
            ZGNTQVI1cFRHUXkyemtQalFmQ3B5YlkKLS0tIEltREhkSGlEVnRuZGdTYzJtenQ0
            aG5NOGR0ZDNDVFRnTWVYK05KaWhPMWcK9ziJ9yFT7WKKm1NZO2pvPMulqEeorBX1
            SrsttDna5CM5yq4krPtk+a7izxSgnjsVfIRVHEtJN69IAr7JKBBBow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T17:02:38Z"
    mac: ENC[AES256_GCM,data:Qe3iL1JMaWUISwetXFS0OW7a2dP7QQmo/Y6P18af82CX6dfay/F/rMzfBjpkL8XxXaMs6D2jGhqeCvn0LravxeHtZcfMlw65P8Pf5jsa1Yorsp+nS3h+UqhemEFx9Tybr3RJgT2HortyhosenMLFaPs/zMcowg2s/lPfbbEn4Tg=,iv:/BC1FplvqNkfGQ+Op8tH1c6j4d8FQSKk4cXF6R4BnnE=,tag:UAS/mGuXiP5TItDLMytnWQ==,type:str]
    version: 3.13.1
