apiVersion: v1
kind: Secret
metadata:
    name: unraid-exporter-secrets
    namespace: observability
stringData:
    UNRAID_GRAPHQL_URL: ENC[AES256_GCM,data:QwpVU3DjOsYIqI31R83nA7inyr3axBOILSFj3g==,iv:tsXzZhjIo6fGetFyd+PqL9Ra9i3OBRQsYt727LIg0Sk=,tag:sMyHrnAiWN6nW2cAv+EVQg==,type:str]
    UNRAID_API_KEY: ENC[AES256_GCM,data:fhKpG3hkiiWd6a50WdNaZKhET/pNRAzalhdce+lJ+EqfSnhJ5wEw7OZJG8qllGK6uQ2XGFv0uyFu9dYZbbA5oA==,iv:ZKeQbkk9NFzDdnKgckHRSwQTWQWP6JwvApBqZqukVF8=,tag:P+gQC4qkISVFreQDqbaDCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTzR4LzZPUU9aQ0tVTmpy
            NW9kd0h6N3hUWVFQZ21iQVJUNXM0VTMrTkdVCmZ2bnZzZzhKaUZlazYxcUV0SUcx
            UmhyNHlvNG05Q1ZVTjBDU0pDVUI1MkkKLS0tIGtkaStJanJVMDhhUE54ZzNVKzZm
            ZlAyVCtKZndid2NmZ21vQVFhSVk3NlUKVC2rs5RsA5Ip7zAGuapFUccVSe+UGAmR
            y6lGZyzFSUT25BY2ZpqT3d5Vr6P/RLlB8IMyFxBPd6GdftDRbGyqbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T18:18:23Z"
    mac: ENC[AES256_GCM,data:9ajmb+aMIs6ZLbfx19g47HC6CMNMkshkb3RaEN/GOLYjYchGkO1X4xnu99nAeDEeXtQW2sAjP/zVYPbzsxSRLbbe2t2KEsuI21muAb+lPU184SnZYGFOxg2573kl4XDWvZtT9jO86vfq1eO/VwKfy0dIeshPa07n+4KFvL9eFio=,iv:k2W1WMwB+xLsawaHvE+NUVI8bBg3WGgl+Cp9GbSAaTM=,tag:n6YBjaj2/E5DXSwER4iudA==,type:str]
    version: 3.13.3
