apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kustomization-bookstack.yaml
  - kustomization-firefly.yaml
  - kustomization-freshrss.yaml
  - kustomization-home-assistant.yaml
  - kustomization-it-tools.yaml
  - kustomization-keycloak.yaml
  - kustomization-mattermost.yaml
  - kustomization-syncthing.yaml
  - kustomization-static-web.yaml
  - kustomization-vaultwarden.yaml
