apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.sops.yaml
  - deployment-homeassistant.yaml
  - deployment-mosquitto.yaml
  - deployment-mqtt-explorer.yaml
  - service-homeassistant.yaml
  - service-mosquitto.yaml
  - service-mqtt-explorer.yaml
  - ingress-homeassistant.yaml
