apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: mosquitto
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.131
  selector:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/component: broker
  ports:
    - name: mqtt
      port: 1833
      targetPort: mqtt
    - name: mqtts
      port: 8883
      targetPort: mqtts
