apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-faster-whisper
  namespace: llm
  labels:
    app.kubernetes.io/name: wyoming-faster-whisper
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: wyoming-faster-whisper
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wyoming-faster-whisper
        app.kubernetes.io/component: app
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        gpu: nvidia
        kubernetes.io/hostname: nimgerianor
      terminationGracePeriodSeconds: 30
      containers:
        - name: wyoming-faster-whisper
          image: rhasspy/wyoming-whisper:3.1.0
          imagePullPolicy: IfNotPresent
          args:
            - --model
            - small.en
            - --language
            - en
            - --uri
            - tcp://0.0.0.0:10300
            - --data-dir
            - /data
            - --download-dir
            - /data
          ports:
            - name: wyoming
              containerPort: 10300
          readinessProbe:
            tcpSocket:
              port: wyoming
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: wyoming
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
              nvidia.com/gpu.shared: 1
            limits:
              memory: 8Gi
              nvidia.com/gpu.shared: 1
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wyoming-faster-whisper-data
