apiVersion: v1
kind: Secret
metadata:
    name: llm-secrets
    namespace: llm
type: Opaque
stringData:
    OAUTH_CLIENT_ID: ENC[AES256_GCM,data:msZHfN6ZXff0,iv:VDrHapATQbBLRvlC24rDzE5XY075KVaaeeusvS7dlng=,tag:IUI+icfQ6TyMZjt0EBpH0g==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:EeId1KcG6KVzb35RxEgAsYAnCfmenSJbN7bJTsmYz+I=,iv:u6NwVGixDRN7l1qV/DSuCPVViOoLpEk4ZWfBUSDGGQg=,tag:VWeJm7sVwFW83WVR6FvDVw==,type:str]
    WEBUI_SECRET_KEY: ENC[AES256_GCM,data:hRjyYgaTUlIW1ZG46kbS+3rAc+PDOanedU1oKHQuQWF75M5829HFmilmN0EMhZHVEjQ15S8eqvH4xad1CzrCfg==,iv:kPJ5O3plnXsrb1ifJnbshc9yrD3GX57ptRgvGtyASVw=,tag:tEXcdE83/YhEnjhyGZ9lbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDNEwzZDFkVTdLYXZkTHpo
            MUEzNXVWazB4ZjVMTFpjb0ZiV1haK0w4cDFVCkJ6Y2dndnpIY3gxMEdHYUpYbUVE
            WVllTUtrSHdldmZOeU5lWXVsRjZsV1kKLS0tIGM4R21MOS9yY3VYQ25VaUpCYW9k
            bWozdEUrMGU4Qkg4MDhiNVVHQ09WVm8K2OfvwRcfXeihJwYoyhTLSGmUHY7eJet8
            01L6a88lJAYSIMOYKs4QkuXWtsanJeWCiAtQR7E+IKVoxEtPGCGFWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T17:32:33Z"
    mac: ENC[AES256_GCM,data:VRcAr5LMOrBGUAyvTUTjSmwfSMKgGnvsAUSzBhcVyAmxZrODjNIqoI8Z5zoCykvbAGMvn0kz0NiHBs03KnvvtFNhNrH/6WxkyzpVGiJrWEUPXvSuB9AVec+s70NQvQErRAkFeK8GRsZmJDK+cBY2zXnzm6AsMdmrPxVnTfFCXgM=,iv:Evjoak4x6xS/rPgpD64U9kqnSHr/R/hMtuFUEcxTizs=,tag:3vRxXpurP4ulYhBMKqFIXw==,type:str]
    version: 3.13.1
