apiVersion: v1
kind: Service
metadata:
  name: kokoro
  namespace: llm
spec:
  selector:
    app.kubernetes.io/name: kokoro
    app.kubernetes.io/component: app
  ports:
    - name: wyoming
      port: 10210
      targetPort: wyoming
