apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - middleware-upload-buffering.yaml
  - middleware-trailing-slash.yaml
  - oauth2-proxy
  - filebrowser
  - beets
