apiVersion: v1
kind: Secret
metadata:
    name: music-ingest-secrets
    namespace: music-ingest
    labels:
        app.kubernetes.io/part-of: music-ingest
        app.kubernetes.io/component: secrets
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:pbryoGH2PiyEvV2H,iv:afN6uqwTrcKUdtYLIsdwSshdn5Ptx8kK+mdYB6AJ2QE=,tag:9E1rb3e7cfGz03BUXT/hVA==,type:str]
    client-secret: ENC[AES256_GCM,data:OxX7U4lbD8RNMM2hkAX6JNi/XG4v3ctPEyPuD/3zrSY=,iv:t65JPG4KbOLQ+LRib/L3fKbGyYWXjaXA/8jzlbdDzv8=,tag:WiRo2eELFOuQecp37m5wqQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:KasKtEV2bsGTxjzfADRKIxwRywENo9fBPX5zl9ezrQnkKScwDLoaHQhKXMs=,iv:4Gta+DW7S2PmjOEVHT9fhqClxq3gMKSZfMoHLUfe1sw=,tag:g1QgbzngGmIwYvk2OiaWgg==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbHU5VUZ4cFRvcFpSbkh4
            MzlVcXpYVmdIRU96cFNMcUs4b0FqSVFERzBjClhNb2M4QzZ5SXZkSm5VUEx5NllS
            Y1RuYlJld0FSQWdmbzdBblRPUGFqU00KLS0tIFEyUnlRWFFFd25ubDFtNWlMOVpy
            N2dHZCtHejRsS0pUajVtQ3pFcGRLYzAKXBHLKxvIx2jB/0NhRdkcT6Yz/KE3jfQ+
            LfarDoncCpKcVlCdmK7VGWfZ8zgvr1PDS1tcDqOIvbxTH7Yqx6MB3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T19:10:07Z"
    mac: ENC[AES256_GCM,data:AgVp3ZIDg/7HrVdyRPdn5AVq4CDXcKym/oZFncHFv1lTJODYyqnQg12CjldQ2kwcZlWnT+G6MKVv+hT7i72ymgZ0eNjXXp5Z6ggXpj5EkWo+YDzA8FOnazximbiCB5Es0Nh5scO208vznwIscU+Bmw53q7CshNe/ExBSb+SM2S0=,iv:FC5cpu50UzR7gFkutOOsVh8PeaE/cM1NM3SyDDuOuKc=,tag:HxtQs3Lwhl33+34UIv2m5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
