apiVersion: v1
kind: Secret
metadata:
    name: music-ingest-secrets
    namespace: music-ingest
    labels:
        app.kubernetes.io/part-of: music-ingest
        app.kubernetes.io/component: secrets
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:pbryoGH2PiyEvV2H,iv:afN6uqwTrcKUdtYLIsdwSshdn5Ptx8kK+mdYB6AJ2QE=,tag:9E1rb3e7cfGz03BUXT/hVA==,type:str]
    client-secret: ENC[AES256_GCM,data:NmtJayZqBa7KST5w60WbFjdATlrueQ/q6EWhXDdzOYw=,iv:zSXYozDCRc6D9Tdkvz2K/tBNokp4F08ufgDSTRg3XQA=,tag:0TyA/C8lfSjowDPRg0i/kQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:KasKtEV2bsGTxjzfADRKIxwRywENo9fBPX5zl9ezrQnkKScwDLoaHQhKXMs=,iv:4Gta+DW7S2PmjOEVHT9fhqClxq3gMKSZfMoHLUfe1sw=,tag:g1QgbzngGmIwYvk2OiaWgg==,type:str]
    BEETS_DISCOGS_TOKEN: ENC[AES256_GCM,data:Jl6LHo04ieUFibTMZXtmKQhS6ubegNtTKssEvVQbpWYeqmZxu0pfzg==,iv:mDaqY6VkIchYZrKC/6wUitvvOPXYjvM9aaLF5l6vJlk=,tag:AkSwH0WT0hrk0WsB4Cq6+g==,type:str]
    BEETS_ACOUSTID_APIKEY: ENC[AES256_GCM,data:MaB0/ry0W/Al+A==,iv:M0BoBM3FkKb9qna0SwQyYBKbUokYBWKX3EYMAlzgb6Y=,tag:PDlnrLzbXUeq2WHo8ckHZA==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbHU5VUZ4cFRvcFpSbkh4
            MzlVcXpYVmdIRU96cFNMcUs4b0FqSVFERzBjClhNb2M4QzZ5SXZkSm5VUEx5NllS
            Y1RuYlJld0FSQWdmbzdBblRPUGFqU00KLS0tIFEyUnlRWFFFd25ubDFtNWlMOVpy
            N2dHZCtHejRsS0pUajVtQ3pFcGRLYzAKXBHLKxvIx2jB/0NhRdkcT6Yz/KE3jfQ+
            LfarDoncCpKcVlCdmK7VGWfZ8zgvr1PDS1tcDqOIvbxTH7Yqx6MB3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T02:29:52Z"
    mac: ENC[AES256_GCM,data:li0WdlyjhvImp9YYeNCj5vRPc/8SbSfEy5rpk2v8nC0pSbLUKJbosN0f8HEALmL4XqpCEb+/1fMDmTkNnmqnKaHdI8poBFB7QDOSYp08F5moPz5rGcsQik5uYcB04keocZLEdJQd6dQpnbeTAPcu9hzyRNZUdX8sDCwv0ww2udc=,iv:bcBHTO221sgyzlWh0bmmHjSNEwpzt2rK+8+Sh80g0VY=,tag:2FlX7+fiiJ99KVfgbLc9Ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
