apiVersion: v1
kind: Secret
metadata:
    name: music-ingest-secrets
    namespace: music-ingest
    labels:
        app.kubernetes.io/part-of: music-ingest
        app.kubernetes.io/component: secrets
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:pbryoGH2PiyEvV2H,iv:afN6uqwTrcKUdtYLIsdwSshdn5Ptx8kK+mdYB6AJ2QE=,tag:9E1rb3e7cfGz03BUXT/hVA==,type:str]
    client-secret: ENC[AES256_GCM,data:OxX7U4lbD8RNMM2hkAX6JNi/XG4v3ctPEyPuD/3zrSY=,iv:t65JPG4KbOLQ+LRib/L3fKbGyYWXjaXA/8jzlbdDzv8=,tag:WiRo2eELFOuQecp37m5wqQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:KasKtEV2bsGTxjzfADRKIxwRywENo9fBPX5zl9ezrQnkKScwDLoaHQhKXMs=,iv:4Gta+DW7S2PmjOEVHT9fhqClxq3gMKSZfMoHLUfe1sw=,tag:g1QgbzngGmIwYvk2OiaWgg==,type:str]
    BEETS_DISCOGS_TOKEN: ENC[AES256_GCM,data:Jl6LHo04ieUFibTMZXtmKQhS6ubegNtTKssEvVQbpWYeqmZxu0pfzg==,iv:mDaqY6VkIchYZrKC/6wUitvvOPXYjvM9aaLF5l6vJlk=,tag:AkSwH0WT0hrk0WsB4Cq6+g==,type:str]
    BEETS_ACOUSTID_APIKEY: ENC[AES256_GCM,data:MaB0/ry0W/Al+A==,iv:M0BoBM3FkKb9qna0SwQyYBKbUokYBWKX3EYMAlzgb6Y=,tag:PDlnrLzbXUeq2WHo8ckHZA==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbHU5VUZ4cFRvcFpSbkh4
            MzlVcXpYVmdIRU96cFNMcUs4b0FqSVFERzBjClhNb2M4QzZ5SXZkSm5VUEx5NllS
            Y1RuYlJld0FSQWdmbzdBblRPUGFqU00KLS0tIFEyUnlRWFFFd25ubDFtNWlMOVpy
            N2dHZCtHejRsS0pUajVtQ3pFcGRLYzAKXBHLKxvIx2jB/0NhRdkcT6Yz/KE3jfQ+
            LfarDoncCpKcVlCdmK7VGWfZ8zgvr1PDS1tcDqOIvbxTH7Yqx6MB3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T22:42:17Z"
    mac: ENC[AES256_GCM,data:D51DvcfO310bbv/BAOMOHm/ADx0GrwQoMtdFPSjQdZyydHBs5N66tRdDGkHMEj1/hb22nK9/kfhxPxWQcgJXmoU+EDlTn/3A8CJGOu/sUeygM6ohC8tUA121jup6o5o38Qlj0x7Dlh5TxiiGmGYCFWN3rjJXJscuWcBOQD0oT/M=,iv:2neYHVJGU0JKjUkFjdUFKOBdbW4582MP//ye/4RiMgI=,tag:CNnCtG1iYjAvzMf50NIgZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
