apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-uploads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
  nfs:
    server: 192.168.1.231
    path: /mnt/cache/ebook_uploads
