apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-uploads
  namespace: calibre
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: calibre-uploads
