apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-config
  namespace: calibre
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-retain
  resources:
    requests:
      storage: 5Gi
