apiVersion: v1
kind: Pod
metadata:
  name: keycloak-copy-db
  namespace: keycloak
spec:
  restartPolicy: Never
  nodeSelector:
    longhorn: "enabled"
  containers:
    - name: shell
      image: postgres:18
      command: ["/bin/sh", "-c", "sleep infinity"]
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: POSTGRES_PASSWORD
      volumeMounts:
        - name: source
          mountPath: /source
          readOnly: true
  volumes:
    - name: source
      nfs:
        server: 192.168.1.231
        path: /mnt/user/backups/keycloak
