apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth2-proxy-secrets
    namespace: observability
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:E34HqPSt/w==,iv:2VzftR6XAK2Qrd+/lo9vEQMoUziVLo83bw3YvXdbB/E=,tag:NoSNoN6vxqxRapFODItfYw==,type:str]
    client-secret: ENC[AES256_GCM,data:XfpKnbeI6XQNJ0+n0gT/4+6bXYRhLa2Ca1ErMRwiS3M=,iv:GSITFNiy6P+bjPeIbMhOUNDnQRm5crBY7u2APaIGBHk=,tag:j69SRsMI/Z2Am1lPzAhVjw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:2kZLH0fwf53u6p9c1rM+dzRSKGJH4IT3xDvmKYErxKd7KhkVmSGZFLI7QE8=,iv:wMlIgMkrUPgmTDvNQeXRlUZb5s8gkYrLHOrn41zlZm0=,tag:cSBL9gRd0CNgTa28iY+3Aw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJK0k4RDdZblNOSGgrK21J
            Yk56eENXWjlENW02THk1a0h2UVY1RXRyUjJFCk95TzVEREg1V1R1TmVjM0IzVVVk
            ZWhka2krRGNYUnV5UVJtSWw1VDZOdjAKLS0tIFhvT0pBZnQwSlozVzh5bGdZb3RX
            YnphRnF5R2RMR2k4TWNDRWZoaGRMbEUKchAPtCndqormhlVycTBeiQKlOgA69dg6
            B7lrVgYyBpvbL3uoXzCfSdagC1MMvlKBvnUwRXk9OLxE4B166XHIfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T19:03:27Z"
    mac: ENC[AES256_GCM,data:HUNI+WNxUTBu79C7GodcxRcB9dw7GNhr56gg9zeYLAQvahZrA8S7K2TKftpGeMjLh2s7GvZgRtfbes+K6xMWrb9JZ27z4jkzRXET9ZB35p+gg9pQoFkHZMzVf4JYVZ9vFZMqGQZAjIvISu4Z6mRyC+GOq2AaPp0Y+uuSjic/ogU=,iv:z32ypA+7gLza/Co7mgggkWmlnApBW3+mzAfsKnkDYA8=,tag:mTKhmK4NblYowjWkni7sbw==,type:str]
    version: 3.13.1
