apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-explorer-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn-retain
