apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: admin-auth
  namespace: traefik-system
spec:
  interval: 30m0s
  chart:
    spec:
      chart: oauth2-proxy
      version: "10.4.2"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  values:
    replicaCount: 1
    config:
      existingSecret: admin-auth-secrets
      emailDomains:
        - "*"
    extraArgs:
      provider: keycloak-oidc
      oidc-issuer-url: https://id.dege.app/realms/theborocrew
      scope: openid email profile groups
      redirect-url: https://auth.admin.dege.app/oauth2/callback
      upstream: static://202
      reverse-proxy: "true"
      cookie-secure: "true"
      cookie-samesite: lax
      cookie-domain: .admin.dege.app
      cookie-name: __Secure-admin_oauth2_proxy
      cookie-csrf-per-request: "true"
      cookie-csrf-expire: 5m
      cookie-refresh: 1h
      skip-provider-button: "true"
      pass-user-headers: "true"
      set-xauthrequest: "true"
      allowed-group: homelab-admins
      oidc-groups-claim: groups
    service:
      type: ClusterIP
      portNumber: 80
    ingress:
      enabled: true
      className: traefik
      path: /
      pathType: Prefix
      hosts:
        - auth.admin.dege.app
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
    nodeSelector:
      node-type: baremetal
