# Copy this file to secret.sops.yaml, replace the values, and encrypt it with:
#   sops -e -i k3s/cluster/infra/auth/admin/secret.sops.yaml
# Then add secret.sops.yaml to kustomization.yaml.
apiVersion: v1
kind: Secret
metadata:
    name: admin-auth-secrets
    namespace: traefik-system
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:8nxiLjZ2F/+Pnw==,iv:E7D7brkureWl1ziTvD4g2sjCiwk9KvovsfZm75hd/48=,tag:L5rKKblP8+DVw8Xh1LvvmA==,type:str]
    client-secret: ENC[AES256_GCM,data:NKtUci9oTGpVrzDpEYhcEPxDxoufal9Jrrgg+67C5t0=,iv:M2fUZhw3o2ugug4+037T0EDPZ/UbdJz/7QdPlgXfu/o=,tag:cE0waAjLxC5bMk7uGf1v9g==,type:str]
    cookie-secret: ENC[AES256_GCM,data:2255xo58DZgu2l8L6AdyCklo2xbXpAq+RjUHywfMiQI=,iv:gyXr2ZIDwccYKHxFZ+B6mE3wce3XK22Yv60FULnLeYo=,tag:FOKL/mSA7dYP23+gqMTX+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycEY2NkpYZXN4UFlQU3Rp
            NjJFSVJvUS9LMmdoMkUvK2dNdTVseXhpUVFnCkdranNJb3hHZlEybktyYUk1OWlV
            aWRBZUZISVdLanRqRm1Sd2xKRDgyaVEKLS0tIDZZSFAzYUhXbWlGd0dBVmFVL0NU
            WnFmS3F2azFYdFVMaEwzRVhEM20reVkKc3bYx/6EL9EImyMEDK6yfCfZWMUH0rPh
            OLfSiOki59TmePmrii09ai2+AM3vygcz0eRmqhXdEadE6yVXliAUrw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-03T20:07:57Z"
    mac: ENC[AES256_GCM,data:9GgcFGEBzqKzo341SvFaOs1AYcIvAQRsdT10slzKJMjgxvYUDdsVfMpzII+1YKixVTGLahSxBMRRbpWwUoVQwUSJKz6Kbvh3nmUSg1aj3qpRFdJAy13Q0sEIqm4sf2+D1nQ4O6yDRN6iCyQyAxcqEjv/DnOu+yFqyljHYvUPXTo=,iv:JJUOtFAXUs2Z5/Tkj87g/kNkE8R+LNtC1OIwvlSNfGU=,tag:ciDpATjL5h1zv3A5NFYdcQ==,type:str]
    version: 3.13.3
