apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pv-uploads.yaml
  - pvc-uploads.yaml
  - pvc-beets-state.yaml
  - pv-library.yaml
  - pvc-library.yaml
  - configmap-beets.yaml
  - secret.sops.yaml
  - middleware-upload-buffering.yaml
