apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-ingest-library
  labels:
    app.kubernetes.io/part-of: music-ingest
    app.kubernetes.io/component: library
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
  nfs:
    server: 192.168.1.231
    path: /mnt/user/music/
