apiVersion: v1
kind: Secret
metadata:
  name: music-ingest-secrets
  namespace: music-ingest
  labels:
    app.kubernetes.io/part-of: music-ingest
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  clientID: music-ingest
  clientSecret: REPLACE_ME
  cookieSecret: REPLACE_ME
  BEETS_DISCOGS_TOKEN: REPLACE_ME
  BEETS_ACOUSTID_APIKEY: REPLACE_ME
