apiVersion: v1
kind: Node
metadata:
  name: minandras
  labels:
    compute: high
    storage.longhorn.io/eligible: "false"
---
apiVersion: v1
kind: Node
metadata:
  name: tadandras
  labels:
    compute: standard
    storage.longhorn.io/eligible: "false"
---
apiVersion: v1
kind: Node
metadata:
  name: nelandras
  labels:
    compute: standard
    storage.longhorn.io/eligible: "false"
