edge_caddy_cloudflare_api_token: ENC[AES256_GCM,data:NFlU8Ejdiuxbavnd4lWyMB+CN2nqs0AlZWjHYvOPmbF9pbt++qekiQ==,iv:cyGcsneZTYxj81hWoH81hQFcDuZ+NQ1jTUq9fQz+WEk=,tag:l0WwQ/WicKkjzZ0K81Ed8w==,type:str]
step_ca_password: ENC[AES256_GCM,data:PGo1I1AzS9oKagL7+CZLv8QVMPCaeuR0tnD+6mKV+JfAgq6pUPjjKTBIF+I=,iv:NhYLuemGc9Q6RK1Ji84rNEnOk8uwwFt/dwORVpbkIoM=,tag:jJKGulNc74Wbh7hcIFLpiw==,type:str]
step_ca_provisioner_password: ENC[AES256_GCM,data:OGPyxzcl6nwLfDPkvXX6BYznUDsuOxH32ND6YA83qomWuxxfytUFfNlXP/4=,iv:aFoAnIDA3ufUyz6mju4rOTnLwDyhQ5opleI9SC6wuRY=,tag:5ntC2Q2G7NVPvqZ7J0Tyew==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR1N2bVdZTEY5RzJ2TVgr
            WExZc1pZZzNhUFh3T1NkRWxWbXRPMGpQU2hJCjdrQUVOUk12L2g0WHBoYzlWb21B
            NlVic2NSMVM2MGxHNi9ZTmNZS0tjVGMKLS0tIHV6WllJQzNDMEhPU082UVZYbUsw
            ZEJxTlpPTktjVVM0dUZYZWFzY0Rpc3cK349lt4AL5DKKMaX4epflVGsABJvTU3YW
            TxFOW7inW4HiXKzH0Yns/JXdvOn82hWJMCDu3jj1vOu+NbLemJ7c1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T13:42:52Z"
    mac: ENC[AES256_GCM,data:QkRzlCBsJbR13wGRvRS1rO+1WMOrXcjLjn0Ym91CYZfFh4nB9VepKlppWxSGF3AAsBxpg/I4jN0fJV81sNPKmr00bhcTeepUbYbbtRAOGu7CbIuxrA7z0rR8yJ23dRQzS4dDzO8Qn7gZKK/O09mPFmNE0f+Yfd530r+NrCNXFkw=,iv:QPQkd03uRlDrOr2EaKsZQGkq6bZJC3cCNwUcx2bsEzM=,tag:srBTgrXkQhK5uXO53MmwQQ==,type:str]
    encrypted_regex: ^(data|stringData|.*token.*|.*password.*|.*secret.*)$
    version: 3.12.2
