apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-web-config
  namespace: static-web
  labels:
    app.kubernetes.io/name: static-web
    app.kubernetes.io/component: app
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 1Gi
