apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: volume-snapshot-hourly
  namespace: longhorn-system
spec:
  cron: "0 * * * *"
  task: snapshot
  groups:
    - default
  retain: 24
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: volume-backup-nightly
  namespace: longhorn-system
spec:
  cron: "0 3 * * *"
  task: backup
  groups:
    - default
  retain: 14
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: volume-backup-weekly
  namespace: longhorn-system
spec:
  cron: "0 4 * * 0"
  task: backup
  groups:
    - default
  retain: 8
  concurrency: 2
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-system-backup-weekly
  namespace: longhorn-system
spec:
  cron: "30 4 * * 0"
  task: system-backup
  retain: 8
  concurrency: 1
  parameters:
    volume-backup-policy: if-not-present
