apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-target
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Xpt4V58y8Ht4UgFV+gG9P1wcJ2rb15hcdVo=,iv:Pw4Q7Y2kvFaTujRyeZwINPiEcAE4w3SLFYh/hZKgDg0=,tag:JZ7YBHrlgx78JkuuywQnTQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xliDEoQge4OX+OAyJHVlBK/YklWvy7U6ITvfxMtKTGLaLTR1Fv2+pKIyKm1y7X5+4Wtp/XlgQYN+MiCpMAgVMg==,iv:gCT8pH5DaLy9Wr/qtN3Sc4WdJu0is9T/qSoOb+Xl/fg=,tag:znDTmjYVSeOcrVnCJxTDcg==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:xmy5hGxg3ZzmnhNT5lITbvxtVo0JplRz4g==,iv:qtTpSBojLWx5O138UhInoUYbfTr5jeLpOHi6pBu2Xy8=,tag:4tn5Sm1C9pLeDHvTCBQJBQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:zx4A6NTl,iv:4f/Srpruk7Wu2imQ5sDFaJJUZywnCrE5cJ8MDA6Yyxc=,tag:9Qd3ACAuqoFoua5gZqlmjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdHdpb045WW83MC9Bc005
            K2Z2dUFnbXdjd1ZDenBkS3FqQUdXYmtmdUhvCnZ1SkYzRXM5clB1amNJd2t4UzlR
            aVkxRm9WTUltbWEzL0lpNjdSVSsvajAKLS0tIEpxN1VHTjdzSkZwZVk5YUVESDAw
            VDFCTGxKL01VaThVUXB4K0N3R3ZJcEUK6gA+1r+LzCM+1ghQbkYovXkn/MlGjWRJ
            ZLWrrJJN5lHVzCtu0CbCYUwpenUF8uwGJXuR3WP7XKZGAHFyc7nGxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T17:58:58Z"
    mac: ENC[AES256_GCM,data:+4q3xr+tIEp7lvhDXKQwkig6Cnj6bm50LNxCA/WrbhoOmfosnzdTXwOshsMU3oycT3GJpkn6CX6wVZ0ccwRqYvc9/aTVe1BNzh8nFzJdDHvlZnXY5GPLVxccyuKX2y//Tqr81O4izMoNYjCAXil3JQy+fe9J3QzAp2OzwZiWvc4=,iv:5d52NGC5SBPZ6BZHEi5x8e2nvDYmh5bjPc0oOfcVBuI=,tag:PGPS6iz23bkpbuCPyRXW9w==,type:str]
    version: 3.13.1
