apiVersion: v1
kind: Secret
metadata:
    name: longhorn-backup-target
    namespace: longhorn-system
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Xpt4V58y8Ht4UgFV+gG9P1wcJ2rb15hcdVo=,iv:Pw4Q7Y2kvFaTujRyeZwINPiEcAE4w3SLFYh/hZKgDg0=,tag:JZ7YBHrlgx78JkuuywQnTQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ML71RokO+hBVap6ctxh2Nr8DUpoduNOSD6UlWd2tfLY36niUE/Tv5Noxo88GaafT8fg/6xHDRVq5ABDQ6VqtTg==,iv:9dvLI3hw2CUIUsoymxU5GamwWtgFFGKu9nTebEDJosU=,tag:31lM0+3K6VTeYw2YYL9t4Q==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:xmy5hGxg3ZzmnhNT5lITbvxtVo0JplRz4g==,iv:qtTpSBojLWx5O138UhInoUYbfTr5jeLpOHi6pBu2Xy8=,tag:4tn5Sm1C9pLeDHvTCBQJBQ==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:zx4A6NTl,iv:4f/Srpruk7Wu2imQ5sDFaJJUZywnCrE5cJ8MDA6Yyxc=,tag:9Qd3ACAuqoFoua5gZqlmjg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdHdpb045WW83MC9Bc005
            K2Z2dUFnbXdjd1ZDenBkS3FqQUdXYmtmdUhvCnZ1SkYzRXM5clB1amNJd2t4UzlR
            aVkxRm9WTUltbWEzL0lpNjdSVSsvajAKLS0tIEpxN1VHTjdzSkZwZVk5YUVESDAw
            VDFCTGxKL01VaThVUXB4K0N3R3ZJcEUK6gA+1r+LzCM+1ghQbkYovXkn/MlGjWRJ
            ZLWrrJJN5lHVzCtu0CbCYUwpenUF8uwGJXuR3WP7XKZGAHFyc7nGxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T18:49:17Z"
    mac: ENC[AES256_GCM,data:TwFW7M0T+UOBl52hoCxVaiSbI5zjrvKzsJIMnKyNvmyXY82YEcZXu2tDR5+1d8rgtIzGOlRJq5jYx1un7TJIVHmKiI3BMUQVIz/MqAnusppm66BqEmmxR+pOGs03t/fjrI+X8rnh3MGXhJxaxtH2barUD5H5oQK78O/yBJhm1tY=,iv:k3zlUclWbeXkzZloy7xg73zWWEzDj+le8xknmQuLUzU=,tag:E4HfuIsjt9kn8LmDESrK9w==,type:str]
    version: 3.13.1
