apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-backend-tls
  namespace: traefik-system
spec:
  secretName: traefik-backend-tls
  issuerRef:
    kind: ClusterIssuer
    name: homelab-internal-ca
  dnsNames:
    - traefik.tadolithron.lan
