apiVersion: v1
kind: Secret
metadata:
    name: media-stack-secrets
    namespace: media-stack
stringData:
    USER_PASSWORD: ENC[AES256_GCM,data:Rx30Lng4UUQvoiHKaP3Q,iv:2CwPfAfZYb69CKQE3g5uOBPIX/f43z39J3a72Bc4X1w=,tag:gAxAldkrU1cyZ1X6iog3CQ==,type:str]
    VPN_USER: ENC[AES256_GCM,data:49nXFBLK0Po=,iv:u9optgy6LkUhhJ1qJYybklW0nwXH1JfBFKBIt0maUGA=,tag:63g2hrfA+xtkQY316AxV5w==,type:str]
    VPN_PASS: ENC[AES256_GCM,data:C48fWB5IKoossA==,iv:Oo4fTLtxDGIFmEC7A19fXcIGEPhLp4dHCsrupSJ2WBg=,tag:dFnRPb3mt272RkYdQSirqg==,type:str]
    PLEX_CLAIM: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bzZYRHdUTFUrMEV1V3lF
            UnB5blVOSzBMYVRoL3FxQzdaT3NHUDlnaXl3Ckw0NUV2M3BNeUxWd1FpNklHaTdn
            T005R2dPKzVCVnZwTXpWWERLOXllRHMKLS0tIFJlcmJiSUdDMDJscDZoMzVEeVBj
            WE1qMDVtdWtrTGVXekJ1eHNFeEkxUm8KmZOuJGZgADL2B6lMlbrArm4Rna50QE6X
            hLeC0AWEUCh5Nl25RmQ9ZcfVt3MsMGJwBa+Y9f6nzlkz/gto4rcbgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-16T20:16:17Z"
    mac: ENC[AES256_GCM,data:i1aoDCKRWXt00sQOlxLgnNzHKyqIxV3RnRqiYVcLKwYrhBE12VLkRSYxS6dURAOIRoetZJS5QRekV4hgmnvq5Bc5JmWjhxssaOYVrbrRT4kM8psQjPwN6rY/Od/8+BjSzA3JwqQpLammRjUs3qgoIs60/xl7uZe0H8buuSjfLEk=,iv:Fx6hYraDn/qhJ0nuOb0QlW9GWsQZW+jtRHtI1SZhJAI=,tag:yx44w6XE4+aNJGAJT9PyFg==,type:str]
    version: 3.13.0
