apiVersion: v1
kind: Pod
metadata:
  name: audiobookshelf-copy-config
  namespace: audiobookshelf
spec:
  restartPolicy: Never
  nodeSelector:
    node-type: vm
  containers:
    - name: migrate
      image: alpine:3.22
      command:
        - sh
        - -c
        - sleep infinity
      securityContext:
        runAsUser: 0
      volumeMounts:
        - name: source
          mountPath: /source
          readOnly: true
        - name: target-config
          mountPath: /target-config
        - name: target-metadata
          mountPath: /target-metadata
  volumes:
    - name: source
      nfs:
        server: 192.168.1.231
        path: /mnt/user/appdata/audiobookshelf
    - name: target-config
      persistentVolumeClaim:
        claimName: audiobookshelf-config
    - name: target-metadata
      persistentVolumeClaim:
        claimName: audiobookshelf-metadata
