apiVersion: v1
kind: Pod
metadata:
  name: keycloak-copy-db
  namespace: keycloak
spec:
  restartPolicy: Never
  nodeSelector:
    longhorn: "enabled"
  containers:
    - name: shell
      image: alpine:3.22
      command: ["/bin/sh", "-c", "sleep infinity"]
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
        - name: source
          mountPath: /source
          readOnly: true
        - name: target
          mountPath: /target
  volumes:
    - name: source
      nfs:
        server: 192.168.1.231
        path: /mnt/user/appdata/keycloak-db-data
    - name: target
      persistentVolumeClaim:
        claimName: keycloak-postgres-data
