k3s_etcd_backup_s3_access_key: ENC[AES256_GCM,data:mP/foWXV3WdN9ikHi7bRdkccKVWv8gkvLvE=,iv:4xXyAJNinBMmW1WPzSSqPaauMQRJThWhTRcG7me4nwI=,tag:VtEOLsJk8QoOsFSJxmCLBQ==,type:str]
k3s_etcd_backup_s3_secret_key: ENC[AES256_GCM,data:fmFGJNl35oIH5OIaXaTAnvFDg3W4sH9ZNrW1/N/E9YaCdpzBgqEMklA94ruJx3QZTqzNJmXm0mVGqtyBWfC5LQ==,iv:tXWOMl8X4FyPbp+w1l3Sx9a/ikJ/SZRfz2Fy2UEJiOQ=,tag:MF4TvCVHV6IsXPuDbUEsMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Mmo3Nk5COWFHc1Nmazdt
            dVd5U3ZrcFpsVUF6WnhzcDQrbEpCam1EdmpjCnBLdld0NEVGNFNsdEZzUjQ5VnNX
            dHp6c3B5ckppMURvaFhVdGllM05LUTgKLS0tIEZuNmVEM1hBNzdlMkQxNEVrZmhv
            TDRmMElGSFJrRk8yL1RDR205bUpCWGcKW0Z89pQnO0e4NuPywbReqgu/9ASZO8+m
            OnTpYX7BaAw3naLBu+SRAQiK0PTzTHd7E0wE7RsmFtStDVFlybAs3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData|.*token.*|.*password.*|.*secret.*|.*access_key.*|.*secret_key.*)$
    lastmodified: "2026-05-17T17:07:23Z"
    mac: ENC[AES256_GCM,data:eVp6h3rPgaiU298Tl3V3/HxPr53NVJHcAlD3drOeE8+3S06ctTqgtrqKo3OB6tvdIqR1ui2UoB05V1GXYV0Sxw7ssPWRe5wJqtEZsV4tZM6vdngGYuWk5kKu2c6adlzUpaKaaBUIsG8ej1Wq19MjBxYNwFIgzcP8vpmeVgtxxvI=,iv:3aAwYGVCQiNAF0PN1wDjNpMh4qLW44Y8DCF58m2wHd0=,tag:fHDkSn651uCZOXVxQDIbpg==,type:str]
    version: 3.13.1
