apiVersion: v1
kind: Secret
metadata:
    name: bookstack-backup-secrets
    namespace: backups
type: Opaque
stringData:
    BOOKSTACK_DB_ROOT_PASSWORD: ENC[AES256_GCM,data:KUJFR41/N0h7VLVLEaMl8/nntdxrew9oAbopsKWNfan+jY238V+Jbac=,iv:SJ0Rp/UwIoQ3J+dXDAsGWnHe5+j9gkgLXubH+NAlk4o=,tag:CHOpZ4zMy5QMa2mTvrXuoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxelN0MFhUeksvSCtpQXdK
            UUJRQ1RIWDExWEhIK0lJOWV3M2NPRko0Wlc4CkxaclIyWDZhUG1KWnNXYmxKZVVw
            amtxd3ArQ2hOdWlFN1lHMlRGalNMVWcKLS0tIEQxQkcrTXdhZ0R0L25XdUxLc2hC
            SGtNa0x1OWk0T0Iwb2MybURMY2Y3a00KWA1uOCF892ajF5nMRJCSH8NjlSFM9CXp
            1Jf929QMSNe9HDtlVKxSXXF1v+GG4jSUPfRjJQjEVPo4MUzu/86sZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T16:57:57Z"
    mac: ENC[AES256_GCM,data:2Jme9P/X2HrWLnrNkmpnP+rrUB/TJVb8BEH5itPsY9TQBwVxU+DBOaPZqPuPqLknImK5b48RMtIO4LxIHJ2zXFGrIdyKB0Jrnglt4/sd3UslO7faAjG4vK7GsL06murNnS7JLFNGBT3MrbgTqoj2ZFBhnYtu9XaE95k75rmiAUU=,iv:2HofZKxKi0FgDrlrN9uHQToyBSQw1oZg90OiovhCFo8=,tag:6qFIoXujZS5w44pNeZo2BQ==,type:str]
    version: 3.13.1
