apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pv-llm-ollama-data.yaml
  - pvc-ollama-data.yaml
  - pvc-openwebui-data.yaml
  - pv-wyoming-faster-whisper-data.yaml
  - pvc-wyoming-faster-whisper-data.yaml
