apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-data
  namespace: llm
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: ""
  volumeName: ollama-data
