apiVersion: v1
kind: Pod
metadata:
  name: mattermost-copy-postgres
  namespace: mattermost
spec:
  restartPolicy: Never
  nodeSelector:
    longhorn: "enabled"
  securityContext:
    runAsUser: 999
    runAsGroup: 999
    fsGroup: 999
    supplementalGroups:
      - 999
      - 2000
  containers:
    - name: shell
      image: alpine:3.22
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: source
          mountPath: /source
          readOnly: true
        - name: target
          mountPath: /target
        - name: target-mattermost
          mountPath: /target-mattermost
  volumes:
    - name: source
      nfs:
        server: 192.168.1.231
        path: /mnt/user/mattermost
    - name: target
      persistentVolumeClaim:
        claimName: mattermost-postgres-data
    - name: target-mattermost
      persistentVolumeClaim:
        claimName: mattermost
