apiVersion: v1
kind: Pod
metadata:
  name: mattermost-copy-postgres
  namespace: mattermost
spec:
  restartPolicy: Never
  nodeSelector:
    longhorn: "enabled"
  securityContext:
    runAsUser: 2000
    runAsGroup: 2000
    fsGroup: 2000
    supplementalGroups:
      - 2000
  containers:
    - name: shell
      image: alpine:3.22
      command: ["/bin/sh", "-c", "sleep infinity"]
      volumeMounts:
        - name: mattermost
          mountPath: /mattermost
        - name: shared
          mountPath: /mattermost/data
          subPath: data
  volumes:
    - name: mattermost
      persistentVolumeClaim:
        claimName: mattermost
    - name: shared
      persistentVolumeClaim:
        claimName: mattermost-shared
