apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home-assistant
stringData:
    mqtt-explorer-http-user: ENC[AES256_GCM,data:139hcGtB,iv:aplz6zNbroAaB5BYHFv7BOsyGRnp+bi6VVX1YiwRptE=,tag:RK7RCrHD9F3k1lPfurTN8w==,type:str]
    mqtt-explorer-http-password: ENC[AES256_GCM,data:a1SyUt9253FQ5Ve5l/XonLmDclE=,iv:SySlb9kefNuHjr4YeUSoPeHrN+zpXfwJCd8gPF1UAh8=,tag:FHPMjgR0KTrYzkgxyLZOXQ==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQTBUdXBTcDdDRjhTQjdW
            WFF5dW1WRisxUU5tOUw5U2o5SmUvRnJrMmtJCm1YSEt2ZnMxMUFzVS9YK1Zaang4
            UEtUeTVHQ2JaNWxlRUNYYTBSSVVjencKLS0tIHBYVWVMdjJkeWpHQnIvVk1WUlJC
            SXNiTkxtN0xJcFZ1b0haYWRWK2MzREkKFphd2nMa85iQmTWb53PPDo9JGwQoorhM
            h8K+tciAMrEQuD37sZvrbVe2KjcN3fZ5MUrznb4bZQYC8KMBQnqq3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T01:55:49Z"
    mac: ENC[AES256_GCM,data:PnQfjttQmV8AXcY6f3vWscxViR1IYFDw+01GuFRHLH3Qs7nTxLMB0ZFD48q/0Q/YvVo/iqLUQbTkjKhc29qLn5dmt9g9DFbY0hshoY6hFgEGH56Gcgkxh6HNxHMIeI3U5f2Kk8YHUp86Gx00Zlxq4rjN3wpW3UmawcHV93PMC5M=,iv:a9sBsnPHKLahPpyCc9gw0XZGj/r92Phvrg9ic92K6kY=,tag:dovaS+1rd7HYeePtc7xeqA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
