apiVersion: v1
kind: Service
metadata:
  name: mqtt-explorer
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: mqtt-explorer
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: mqtt-explorer
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: 4000
      targetPort: http
