apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
  namespace: bookstack
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: database
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-3replicas-retain
  resources:
    requests:
      storage: 5Gi
