apiVersion: v1
kind: Secret
metadata:
    name: bookstack-secrets
    namespace: bookstack
    labels:
        app.kubernetes.io/name: bookstack
        app.kubernetes.io/component: app
type: Opaque
stringData:
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:6mlslbYKBTUlOhuNdqsDrmq+8UDPmwrN8C1QLIc7/Wd52f2hwvDx93w=,iv:mwnRKmMSA05vRE16fDDMAWnPaETSQIXq0lzhm32llxQ=,tag:yMz+45ThE9Ncf26KbC13hQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:KeeJs/s0qeu9BFFoVll9mL78ThFXh/Q+qjTrLDQQSaXShG+B,iv:OMWcYSJgnRiV4weO5UYqQqKBWC8Tkn/oCKZXT4+R/vA=,tag:VmiO6St+md3aQnULLs8ZbA==,type:str]
    APP_KEY: ENC[AES256_GCM,data:0ipVu40KM0EiF3L1C8W8sY/u4kFHlKUreWRKx+eASZP7K4/Ci+VwiXcM2gUqgIFr0+nX,iv:Z6pRTzbnkeG5g0ayc8IVBTsH++5k57ed6DwT/8cJwgI=,tag:2YBq+n6G3gy4R+FIph8orA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:vv0BCZbp/OuDa6fpvZrk/tk4+2iQBHweK57Iaml3X87uIWmD,iv:N5r0yD/mlqwhSfe6TS1xV5Ba3Qemy6e1l7ztXjPX/Cc=,tag:Z9LDfxfVHDExsHQlJHaSAg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:FGThtP3enrblDRVOtgO+ipAe3eRXCP+CS3cKbnvN16g=,iv:trT1U/u5CiIWSEDlfKyIzkn1QE1HAALCaFOINc/HOlM=,tag:4kK3ga80hOXgM8iW/K5aSg==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSkNKUFloVnVJMVE5aWlE
            Z1JKdmtieXZGb25BT1prMFNNV29ObithUEFvCnVwTTBBM3krMk1ieWdycERyN0hj
            aUdnK3hTem5SM0Ntbm5ZMjJkcHd2TkUKLS0tIFllWEZUNXptM01hV3JpU3lZd25V
            TXRBR29zQVJSM1BZTFhGeWhwQzJ6K0UKrNXPpah/No/tOgSloWMLaKP7K22JCP+x
            O1bqa9R07I36OkV57MeyqNyIwz0D1gbv2TwqzN2QDwSx1CbGnRtecA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T18:29:51Z"
    mac: ENC[AES256_GCM,data:RRJ1drRyXcelkB/DAer4AlEdupO48sV6rgFXAeDjA3dFOHCgwiRWQVX1Tk3/uNce/yn0mWKGMbKCzBnEl9HkELFFCJ1p4D0xKVx7Tu6gBImCtyjp3ouxzqB3DIE+y63tDVQyGL1Tij4w+HmTMjQyTDfsXL4BbrhJ5qmTTI+aWvE=,iv:U2FpkwenMt3pDVUmWMzjHLJCXsBQQ8SBHu+J5/vK5XI=,tag:8F/qYQ7bmAG6t0a6TYvVew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
