apiVersion: v1
kind: Secret
metadata:
    name: navidrome-secrets
    namespace: navidrome
type: Opaque
stringData:
    ND_LASTFM_APIKEY: ENC[AES256_GCM,data:m/zSI6gm2tynGNfGDy8WoExaXds+1rlOa3FMdAgNhvM=,iv:beWOxthg5FDmoTFvY3MoWlBdFtL/3TLklGjUr47qVMM=,tag:/CunYXbEyGd8CZupQ/YI3A==,type:str]
    ND_LASTFM_SECRET: ENC[AES256_GCM,data:jUhC6I04qbiL92uHE22b1QEQ9OqwmTmz1RpcJ7DEDMQ=,iv:HT59El0F98AwV7HMG/R3S8/2+sUl+2tt6dXuuFFw/X0=,tag:v6UsyET01JwFhp1Y0XEpkQ==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeTVLTG5wQ0JHZE9wUmNY
            V2FTSFJYeHBlN2hPZnhTSU4wZzJibXJ5QkRJCjJIaVNzN29qL3ZrbnRJQXVJdUtQ
            WS9COXhHbUFMS0dHOEREdXFJN3dFdlkKLS0tIHEwNEV0UEp6YzI5UEZObll2dmVX
            bG42dHo5bDRFM08rbUZhcTFubldrUUkKH1UyjKE2rP5wjoYZebf2Dex4zzgWwIaL
            kMd3tD/J4fAPKtHJ33XdEiEvq+urDUCRjN/ATwqJ2LnD7AntvWlg3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T16:37:11Z"
    mac: ENC[AES256_GCM,data:/+WXjZKxsJXWd450mlpNgznxQosEfGN/KlMtmu3mSk6PtZMKu8NNcfR5uZYUFPV+eDa9y8UFyOu8Y55VSMrk3YKN6gdMWR+19FKwBmFQbQzNUuYzDlkabHxDnB8MXtKfQpPdzW2UdfbTDT6EiBbq24nHLHwl2WLAg3oLb3Yv/Sg=,iv:Kt26lYRclL/xD/Vegn+lXbUzjbvmPizVbofMn1Kzb1U=,tag:OlSLCxt7dZXhnxUBdEzBXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
