apiVersion: v1
kind: Secret
metadata:
    name: metadata-postgres
    namespace: music-ingest
    labels:
        app.kubernetes.io/part-of: music-ingest
        app.kubernetes.io/name: metadata-postgres
        app.kubernetes.io/component: database
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:NvuEFGJPjpYW6U3yf/4=,iv:8whTyJYb9AMnbzFM0whIG61Q6xY5xCdO2J3sHZhnEo0=,tag:fojqV/1HFAxY4KTVfZ8XOg==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:cypD9BSIbBHNZY7GbXk=,iv:ihJgT2Q9CA/Ot05gi51Nnkq4ik1NAQQsWW7DAh5hIJ4=,tag:Sviel3kwJSttr3Mdj67AQQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4UC+olnDFiQ9z3rUXL7jFwTeaVhXuEYaE8Oh8N5x/QklZGMbjhGHCZLTY/hU4g==,iv:V5kGuuG8OTPnD5+wK+6ds7WiXqjnNbqlMZ5RtyA2vdc=,tag:bLsuh5VBGijVZ/I0JEg+0A==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QTdQOVFQY3FzR24ybXhh
            RCthK2I5emtxMzljeDB6Mjk0UkhoQUpCcVNvCmRBMCsyYVIwNFZLOFFCR3c5YWth
            T1B3WkQ3aktseFo1eWhpYmpFTFFMNVUKLS0tIHJVMDRRaTFJVGk1NFZoeTY5T3VT
            RGdkaVFOQW53S3V2cGR4a3BXRTkxclUKaD17bxiDlfwIJYagRmJ5sbaWCTVKFhEp
            eBpBsmMr+UtuhFT4FeR0RWcRkMUdwNPsUFB/E82jMU52QfeuyrC8Kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T00:20:39Z"
    mac: ENC[AES256_GCM,data:9mYvsNX89Q+dGEKr2GHdmG7SnTGb8Rg13lQIry+YcB3t8qb7wEAZi3IgmTdK78yjxsmgUTPAgO5Fm7cLi3b4U4uVvNv06vFVr+5hq3sZWoCza+tDcbN0ipSij9IG/Fqcm5jdnTvgNCN2/ASN8ofK1SedViM8wFCCQzIme0gzbKA=,iv:0PRNxBO9sWz6T3GzasAVlsw6tDzfVnkBWFYiF+so8VY=,tag:gUICpzyuZeDqDkxlx82o0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
