apiVersion: v1
kind: Service
metadata:
  name: metadata-postgres
  namespace: music-ingest
  labels:
    app.kubernetes.io/part-of: music-ingest
    app.kubernetes.io/name: metadata-postgres
    app.kubernetes.io/component: database
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/part-of: music-ingest
    app.kubernetes.io/name: metadata-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
