apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pv-nextdata.yaml
  - pvc-nextdata.yaml
  - pv-ebook-uploads.yaml
  - pvc-ebook-uploads.yaml
  - pvc-nextcloud-config.yaml
  - pvc-mariadb.yaml
