apiVersion: v1
kind: Secret
metadata:
    name: longhorn-oauth2-proxy-secrets
    namespace: longhorn-system
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:l4XjBk2/Iio=,iv:XbQIz1Ob4hdannbBUWjZK9kDufIdAJ7VDukJiFhGGzE=,tag:Awfv0jUKDwogoNU7pCEOIw==,type:str]
    client-secret: ENC[AES256_GCM,data:ZbKw3aimfM24lmCQRbOlCmQBAtIp2tMBau0cC4DaWAk=,iv:J+ZvCLFCkJUwOCX65aaxOXLKaEvien6GzTywbVxXQSs=,tag:5GIDsJToQUeGKgqgi5fI3w==,type:str]
    cookie-secret: ENC[AES256_GCM,data:RSR02RWdJjy6RhP3MbMEkMvypjxRoI9d/kSyz2Jf+Sz7OvHnBVSgrXeOvXg=,iv:ATgYPVrlvYw1PVyIgAAulZaf2qKoqloxp893EZ6dZ+A=,tag:wM9TieuIVdvLtMu8aKUOgQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoR1hQaWIxV0ZkRC9DaVJ1
            aXk5NWpFdSs3SDl5cnFIMVBwampIbGREOWdVCk9PSUdCNXYzNzFXY05TbmN3YmN3
            Y3pSVGdlcDhxY0pCMzluc1pORlZvVjQKLS0tIGlxY0ExMUJNRmRjK2Q4TE91WTlR
            MGFhcGY4S0YyV0V6VnU0c2NUY2VialUKGi7yu7mb7fRcE5avNbXC+Gb6RVxW4JZY
            fZZdhtoQJoNUWAKF/yi8FOBh4MDXcDg5f8UgR4UDYNkBngMKnLS5fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T22:24:10Z"
    mac: ENC[AES256_GCM,data:gVhZ+v4UqPIJPult07mvA8hUt8PS4VBKWJ4pnXqKWO8h4LX+L+CFo2X4jOXosF5SXvMyaqNNxy+dY2M1l8M9Bjg33PtfUsWZzXDr1Qy3CJuzWW7IN9Ly1KLYidIRs7rCfKv8J5WQQ2M82pnC/Epg1BvkyGWN0+A84K0hoLL/2nI=,iv:huJnourbsQCXCd38070Fomuxu7wk0OhghOY/oTPi/jI=,tag:27rkfC5+tWtJ5GM7Yq+YDw==,type:str]
    version: 3.13.1
