apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picard-music
  namespace: picard
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti
  storageClassName: ""
  volumeName: picard-music
