apiVersion: v1
kind: Secret
metadata:
    name: picard-secrets
    namespace: picard
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:Ozzn7BR0,iv:vMbDK2BPT7f8v2KG9Gg0H5j83PJz+u84SaicNJ6HemA=,tag:vxIPW3aJOFnFLQSuCyEglw==,type:str]
    client-secret: ENC[AES256_GCM,data:/riW+/Q9woUtTSVipJZQzRXyiwXbT4qtgwOJNE23H98=,iv:Y4M09LzgK+KCpX5EnjL/7pnayBKvFb9Xl5Ef1W9mnRE=,tag:Q3LxVN6imxYiZLlflV8R7Q==,type:str]
    cookie-secret: ENC[AES256_GCM,data:xAd3bLEpvu92Rkto0QagHY9VSJ9QP1t0fy2AeSposnlNftD24K9AdRtP2B4=,iv:3lxChtTlgQHyp8uWz5VFsQypDdkZy6cj8G/CZX+CPsc=,tag:8x/wCdV+2u6fV1h6Ftom4w==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV0NvNG5VSmpMWTh0aEpm
            eWRFd2RmVVRIV0xxb0d1K3pYajhPSDFOOUFjCllFQ2szdEtvQXBLcmd2bW1hSkVV
            aTlaMUQ3cUR6eDRQSW1iMXJiZS9TZTgKLS0tIFF4RCtucFpKS3lWM3A5MlNGOWlI
            OEZ0R3FBa2Q2NU9xVEtjdkd2c1JSYzQKddU5eyMqT7HKQAoCCZCE2r80HOl4lnyO
            bp+srqUpAAUgetLo+Sebon/Voeyl2FR7Q2ZuxBo7nIWnhkKoWQYjnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T16:53:26Z"
    mac: ENC[AES256_GCM,data:KoJsNyzvKT+ULSVHVooR+kVkJU2O7C1ts6kok4+fY1ytLzH9qIgThJOZxTs7JmVpxVEUECrKZ8F0DxmOcC/FFFeNwqEHzDSZ9hem7VehIWoLzVDN82XG/9j6tU8ghGvpmi37PEw7uC49KKiEAnGQ0q/cgD3hpNU+R6A81Uy6kFk=,iv:kDKR1RLWfiIMkakTPi65ocj1Wpb6DXSneYWAtMJT7JY=,tag:K8JcTr2yItE+pLW5ldN21g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
