all:
  children:
    k3s_servers:
      hosts:
        minandras:
          ansible_host: 192.168.1.245
          mgmt_ip: 192.168.1.245
          stor_ip: 192.168.3.101
          mgmt_mac: "64:00:6a:88:13:a7"
          stor_mac: "02:26:26:02:2c:cc"
        tadandras:
          ansible_host: 192.168.1.153
          mgmt_ip: 192.168.1.153
          stor_ip: 192.168.3.102
          mgmt_mac: "64:00:6a:88:37:d2"
          stor_mac: "02:26:26:02:15:b4"
        nelandras:
          ansible_host: 192.168.1.103
          mgmt_ip: 192.168.1.103
          stor_ip: 192.168.3.103
