apiVersion: v1
kind: Secret
metadata:
    name: picard-secrets
    namespace: picard
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:LrTNB5D+,iv:lGAp7ZA3KYVWKIT4l4QjkA5eR+x4lw+8+K/LDdLuyUw=,tag:A60J8KUXtRtqrDL9Ne14cQ==,type:str]
    client-secret: ENC[AES256_GCM,data:aWuchOyC3ukVjxMXLmQuplukcykuC3cbeOLwmDEo9c8=,iv:m7V1sgm7lATssy1feCQAYwj3QR6kHX8PfUu3yL1bEd4=,tag:soLxrEzrK879ib6ZWICYtg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:3+cD5vPJ69YI5P83CyEiKN+rJYtky7jtus7he3aZrCa9RgB+8YI/kc4lg2k=,iv:ta1CmuY8rDd5VLHQyzWkbrDapg0byZWmhKA21tT3qAA=,tag:LUNCS8V2tVY5rzn1/F4V8g==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV0NvNG5VSmpMWTh0aEpm
            eWRFd2RmVVRIV0xxb0d1K3pYajhPSDFOOUFjCllFQ2szdEtvQXBLcmd2bW1hSkVV
            aTlaMUQ3cUR6eDRQSW1iMXJiZS9TZTgKLS0tIFF4RCtucFpKS3lWM3A5MlNGOWlI
            OEZ0R3FBa2Q2NU9xVEtjdkd2c1JSYzQKddU5eyMqT7HKQAoCCZCE2r80HOl4lnyO
            bp+srqUpAAUgetLo+Sebon/Voeyl2FR7Q2ZuxBo7nIWnhkKoWQYjnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T19:29:36Z"
    mac: ENC[AES256_GCM,data:LsArJ+alOuAWAof/ZMbfQle6k9CBkZKstc/wGNe3a4B1OvquUy2URiExO0ABAxIuDvHO/UltD49m+kMe2Tprq4rTN3CVdrARbksEhA7TLYzAugv2gSOQ5Yl8gwGBM8Jk1JHLpN8l2dEDSz7msXtH0Nl/lBgo0GA6gKbzLjOb4IM=,iv:y26TZTV87vkkH6GQT4Z4Gu+h43q3vw8lj6sDhGIjhvQ=,tag:aXaTUZFNydzldPgPqhu+nw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
