apiVersion: v1
kind: Service
metadata:
  name: picard
  namespace: picard
spec:
  selector:
    app.kubernetes.io/name: picard
    app.kubernetes.io/component: app
  ports:
    - name: http
      port: 80
      targetPort: http
