apiVersion: v1
kind: ConfigMap
metadata:
  name: freshrss-config
  namespace: freshrss
  labels:
    app.kubernetes.io/name: freshrss
    app.kubernetes.io/component: app
data:
  TZ: America/New_York
  CRON_MIN: "*/20"
  OIDC_ENABLED: "1"
  OIDC_PROVIDER_METADATA_URL: https://id.mdegenaro.com/realms/theborocrew/.well-known/openid-configuration
  OIDC_CLIENT_ID: freshrss
  OIDC_REMOTE_USER_CLAIM: preferred_username
  OIDC_SCOPES: openid profile email
  OIDC_X_FORWARDED_HEADERS: X-Forwarded-Proto X-Forwarded-Host X-Forwarded-Port