apiVersion: v1
kind: Secret
metadata:
    name: freshrss-secrets
    namespace: freshrss
    labels:
        app.kubernetes.io/name: freshrss
        app.kubernetes.io/component: app
type: Opaque
stringData:
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:qFuQOVdyRzZlmX9p619R9MJibGUolKnSNA/i97tTG/8=,iv:cqfFhmM380IrzXACOaB98Mu7PQQbHuGmLoc8Nk7LSYk=,tag:hhazq6k+zoaA1+US/7cYLg==,type:str]
    OIDC_CLIENT_CRYPTO_KEY: ENC[AES256_GCM,data:rZ2GB/eWakOvsrcAOv2cf/pB/JVHD2k0Z5Qk4qxGx9pkzO0iCQ==,iv:0zCfVJM2svCAxa0iTNJT4SI9OAktdurQ31NZF7DgyN0=,tag:lu0GU+usBMHUcC3gozaWMg==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU2lZZHhjVkpRMkI2dVhk
            Mit1MkYzR1Q5b0g5VldsdkVyb2tnSEhjWjIwCkg0cEVTL2g2Y3RwaVlvOFcybHVs
            VjRJZXBzLzg3VXp1TnEwSS9ZRDdEZzQKLS0tIE05aGNQem15ZTFhenFEK1J0YkRo
            bWJTNnBLbXlDWTdZUDMyNHlDOWE3ZEEKcNaTL7Qivh4cNMOS3jA93a+Rn1xc8Yjy
            hGOz4I45JIESI/XhhGN/Ihsb1DhActEs4G7XCpmVaMk82ZySg6+VjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T00:26:11Z"
    mac: ENC[AES256_GCM,data:vPHkoSKfqarwZanl2MhjshhAgK8YfF3TV+zhst53vU6NkyOZz4GO0mrwjcLlhEksTe6ZyEBH/aVrrjw5cJyqvg3oc1wOCcsRC1qn7gM4YhMD4Nb/pWC7E8A5pJ1LUUUh9uvX8fL8ZMOemSQBOfI1PJdTmdqpSrgmmJHpDFQ7S4U=,iv:eBXX0vZ5QZlVV4RG7IBneD2UUPTP4dZW/uSnKqSzr5c=,tag:Ii9FoKMqgQ7d/5MA/FF92w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
