apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.sops.yaml
  - deployment-firefly.yaml
  - statefulset-mariadb.yaml
  - service-mariadb.yaml
  - service-firefly.yaml
  - ingress.yaml
  - cronjob.yaml
