apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-backup-secrets
    namespace: backups
type: Opaque
stringData:
    NEXTCLOUD_DB_PASSWORD: ENC[AES256_GCM,data:SJvd2YduKCxOc2TQ,iv:l2nq1yDQ7kgqSiuRRHl0FBPLwNFlTGpivFP2EyhOQlc=,tag:G3yW8P4lnvm4udq5sXdjIA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT2g5WFErb2NTTktWSUN0
            dFBtc1ZFWG82bEUyNUNLd1VDa2c2Wk5rZGgwCmNjT2FJV0JBU0s5ODRUZ3A2eWhS
            aEIzN00vdElKeWp3SldlUXJ0V3JyRE0KLS0tIGltWVBWWmdtcDBUb1FLVHc1d3Za
            bTM3WHlQN0dQREJTQ25id3M3YzVqTFkKg05DfC/3DeHzAvOIVuKHW9jC6kgqzOF0
            R4SXNExZb7QwD1h7BaSOP1aIURHcZrD9t+lbeLG23optQ978OH+wPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T20:43:35Z"
    mac: ENC[AES256_GCM,data:9Bb9p0L8L6ZfVkZc1rr7rzodJ2Og46QqzuwMZl+EVwYhLpEtQ4RwOmZZnfvacedpxy+7MRYIhOrlqrDLkDu58pyvpItDHesnmfSz+xARyInC+I8vsW1ElaHXSMlxA6Itu+fF/WSB8wkKwgQ2dyz2J1/YPZ4lvq6ZDT+yqnwTHAM=,iv:XIswNt74KSdpIiAf/kO9KXlOzkPqbRN4iclA0Hy/NBA=,tag:9oRj0p1VbDdbvgQZiLO66A==,type:str]
    version: 3.13.1
