apiVersion: v1
kind: Secret
metadata:
  name: ntfy-secrets
  namespace: ntfy
type: Opaque
stringData:
  # Comma-separated entries; format: <username>:<bcrypt-hash>:<role>
  NTFY_AUTH_USERS: "ntfy-admin:$2y$10$emi/x8irxrXDFROb3cLIP.G4dvFAdI74Yv2EQRIaFj1v.uZ0SqZum:admin,alertmanager-publisher:$2y$10$UUOKkGPgg1Ok9wa6ufRTAeLoAz7rK9i7fv1tQ0ilcoBNkPt85WOKW:user"
  # Comma-separated entries; format: <username>:<topic-pattern>:<access>
  NTFY_AUTH_ACCESS: "ntfy-admin:*:rw,alertmanager-publisher:homelab-alerts:rw"
  # Optional declarative tokens; format: <username>:<token>:<label>
  NTFY_AUTH_TOKENS: ""
