apiVersion: v1
kind: Secret
metadata:
    name: ntfy-secrets
    namespace: ntfy
type: Opaque
stringData:
    #ENC[AES256_GCM,data:AhTacNKEKkLW3Ueu7bVyBpFpYmP0kQJjjd4IZHFJCl/dwCYdD82ucyXP6wVxSGn8QaQdQitPcRyP6paI0+oizoQ=,iv:PANu4FCdcXh04rSt3QmqWkghIHPB11SjH8/ch3U6afI=,tag:dBinWya88eeVjXWrgrU5mA==,type:comment]
    NTFY_AUTH_USERS: ENC[AES256_GCM,data:eH2qIUduzWH4Gk44K87Z/vBTvQ1whDTDG49vtY/0ob5xxNxlYm1dL1y2zduAEJ7uLrZkpaCowfGBGNYiH4ru/3MjcC8iDADZCWjXqnvh7Icit34xkStzil+uHjmwOZZRS/a2SrbYTqOjpfruicWmZM3h90swic4EzneOhZ/RdTJQstSr8sJdlvKvhlGjFxtmZri84mLjXAugKKAjqNTptwKa+dhgKA==,iv:BhKdty2xLS3nJb5y0ahumeFds7rroTzahrHZzR4pq8A=,tag:Fhj4TDnnFIX3wilunKYGcA==,type:str]
    #ENC[AES256_GCM,data:25AaHgUOkGf99qecW7+zMVnFOsjIzAMjFIxNrDuKrMSfJ7jlrJWK1WvNQuN3utWL9Rtyv7Mp77/CWgYPndR2/PHjg3nX,iv:8AFqTnvDoFJwBNXgsrKYwJiGzWDn4iLG43XH0cHmbNA=,tag:lzB2BmaFN5TblhKcIc3jMA==,type:comment]
    NTFY_AUTH_ACCESS: ENC[AES256_GCM,data:Ec3eWgBR/jvUdSUOUUydLivd5JfEloHzkD3ytLzyN+eYUPeEwE6PgQ==,iv:sQqtrT+HivRowaLGM8OPFWN/p5T8WfQ2JKHyp0KGhIY=,tag:fQbPXD9mluM9cJdKuY29TA==,type:str]
    #ENC[AES256_GCM,data:UCxvhyl/WS0hZshs4u0kdxMNmvtDCTh8rmy+BIPDKjHgKl+Bs4eBv3TsYPPBcENCBz09W4ESPS9dZYzrGw+ECg==,iv:4nZtURnCQ0vc3JwHgm3+hCCMHB9OadAxKWVWJPYLLkE=,tag:5BeVnOpOEAN8q3vhTRK9Bw==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNk1hMVRVUllHQldrN2lS
            V0J6SnhneitNL2ZkMmhPTm9QNS80U3JMSFRRCjdlUGJMaExsV2ZTN212ZWVZaTVz
            NDBPSFQ4dk92QXd5NzFDclFmUDBJNzgKLS0tIGhBUnJ5b1pCUmZRY2ZWSU9qZGd2
            Z3IzT0l3Qko1b2FDWU1qSWJ2ajltZ2MK2HRzcweyAWFdqfWCq2FrWAPFBKCVS2SJ
            Q4UXUTdtxY8ogu8/eb/GBIyGtK7OQMC5lqCGOxz7BavKL3EzqawOqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T02:28:35Z"
    mac: ENC[AES256_GCM,data:cF+q2za1oG+SLB1J9G1HD++dRX/L+lIx/ocRC3K+yCFCsZiOifqMan1MojKaucrMrcbEsmWVrlXK/SH1iEn3KePF6mvEpQimFVdWYo2tOwPJnK5rnHIFrEMyAF34D0xvVyU0RAQaeOwZUTVcodhj0jP7pCwSdtegyy+LXN5iQZw=,iv:e5OlO483+0lH2aIoOGw3tUFDst1jZkAlUtsHnCE6rSc=,tag:DFywzQU/TIJNLfu/7GTsEw==,type:str]
    version: 3.13.1
