apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: app
type: Opaque
stringData:
  POSTGRES_PASSWORD: change-me
  KC_BOOTSTRAP_ADMIN_PASSWORD: change-me
