apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-filebrowser.yaml
  - deployment-filebrowser.yaml
  - service-filebrowser.yaml
  - networkpolicy-filebrowser.yaml
