apiVersion: v1
kind: PersistentVolume
metadata:
  name: mattermost-shared
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
    - hard
    - nointr
  nfs:
    server: 192.168.1.231
    path: /mnt/user/mattermost
