apiVersion: v1
kind: PersistentVolume
metadata:
  name: picard-uploads
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.2
  nfs:
    server: 192.168.1.231
    path: /mnt/user/uploads/music-ingest
