apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picard-config
  namespace: picard
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
