apiVersion: v1
kind: ConfigMap
metadata:
  name: mattermost-config
  namespace: mattermost
  labels:
    app.kubernetes.io/name: mattermost
    app.kubernetes.io/component: app
data:
  MM_SQLSETTINGS_DRIVERNAME: postgres
  MM_SERVICESETTINGS_SITEURL: https://theborocrew.com
  MM_FILESETTINGS_DRIVERNAME: local
  MM_LOGSETTINGS_ENABLECONSOLE: "true"
  MM_LOGSETTINGS_CONSOLELEVEL: INFO
  POSTGRES_DB: mattermost
  POSTGRES_USER: mattermost
