apiVersion: v1
kind: Secret
metadata:
    name: mattermost-secrets
    namespace: mattermost
    labels:
        app.kubernetes.io/name: mattermost
        app.kubernetes.io/component: app
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tH7hO3y+5dvX/hP52Aa8PuBAbd5cVw8PiDc2ivwA1qM=,iv:OxJZEMWAOVHlkiBZRfz5vONuY2sPGRSHrVwfEDvj4iE=,tag:2G7Kf0NpaP6q+jv+3JkE7w==,type:str]
    MM_SQLSETTINGS_DATASOURCE: ENC[AES256_GCM,data:Kz4V7zkATp0ttZU5H06gChaecwPixAkvGoPR4EfXYWDRrATBqXwmVdF7odkH9oupqXEuENbzcRVA2BAQU4MA4VeKqDh2hHq1iQ1jbuNUGSCwZciHLoPt7yyc08nrEkq1/aQzfC+kK7UcAootxDvqwcvH,iv:sjQE6Wj/k1/DaOpopCR1XenMDZpYB0NbE/25w+LutMY=,tag:fBszaWuJu7/iLAuRCrzJyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwUXhwMHBPR2lISlFXREZr
            bEFhNk9zYmh5Ly80Z0Mzb0NLNWk0SWVZdUFjCitkemR4dTNFeXl0R0NMck5SbFZj
            ZFJjamxhQVUzMitVd1NzWjJxMDI0SDQKLS0tIHNqTVE0VWZuekx1V2ZxZDRyN2dW
            NFkzZUNlS1NRZ3ZnWk83YklRWnRlSEEKIYEZY2XA67Sh6NryvIvfenqrlC7ZiHfI
            BL+BcrkIlJfflWBvcSOvMi8VEEPivu0vJtMuAaIxPT6ZT0jJdqV29A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-12T18:58:23Z"
    mac: ENC[AES256_GCM,data:7CDEifwAKUJcj7+DkXhkmDneYyU3E53hoc3iT+zIw9jSK4Lj1wxVGk+Avw///VcWHrRavlgaKv5qPZTel2FeqdyEosE6SD4Cm/vJaPr9TxFAGOfBNKJOXHQoblIROCr48VlBHa+Y4fg94P21GoErVv6f0HM/6x/vQLA32ELedSk=,iv:g3SaqLsAn4ocyEvwKw4ydOE5xVNOlIw7hvOTvlgfEsQ=,tag:BNOvbvGeolP9Z2fRaJ6/1A==,type:str]
    version: 3.13.0
