apiVersion: v1
kind: Secret
metadata:
    name: firefly-backup-secrets
    namespace: backups
type: Opaque
stringData:
    FIREFLY_DB_PASSWORD: ENC[AES256_GCM,data:DTmQyPBn7I6ShpU1Q4C8TXmiaF0Ucvvuim2cVUDpYXnthk7hwg==,iv:irgPPIhIt7u++7Twdc33aQEOM9B2WNy2Jw8fSVF1gsE=,tag:FXLnG+p7vw0xWA3a2ZCFuA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3VTVEL1hxWXBhWG1mM2da
            YjN2WXppcjBVOFc1R1ZOMHRUbXVyRG1sV3kwCjRyUHpNK2dYYnlZTkdmRmtQRkl1
            T1VReFVWME9Rbkd2bC9GYktuZEI2L0kKLS0tIDdMemowWlNHWVNpdngrd1l3U05l
            MlFLd0pRTlRYMDhRWnZHT0RHdW11c28KVVAZIAQkjh/6gANZvwzaNe12QJ+j0bKd
            ixQEQsCgK3e50YioRU9euRhmLBQf5LARm74MP3X10ODSkh+JMZIicQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T16:50:54Z"
    mac: ENC[AES256_GCM,data:/WyAYYG5kbR5G6APIm2ZDj1VsTi5/QQ/csjK5ZSCKH/jr2BoOj8QAMveUTn3EoEaeWP+0UDc5UjxmxQ61NYtL2PdnEeMEIZU5SFMiehPWnMCrQnYq4tvngpzCdn04W+tvNiBi7bxRxLCzAkxkvoI8esPbyAwtsmJEOH+gQkP+LQ=,iv:Igolrq2oEedlot8HNizHBcAffTgLpFuj01o6PVmNh0I=,tag:jLL5rGx0eZHXg9zYyMx1aA==,type:str]
    version: 3.13.1
