apiVersion: v1
kind: Secret
metadata:
    name: prometheus-oauth2-proxy-secrets
    namespace: observability
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:1X2EtEHwo1h7Fw==,iv:7z4RYzgp6WUwrGrhm8Evkv8vhTULq3eQ0xn1lrqFFEc=,tag:je14MV/4+y0qWrEN8SqPgA==,type:str]
    client-secret: ENC[AES256_GCM,data:dV/zyBV8UPS1svil1P806u0vBHC/jx43okPIrAgEXDg=,iv:yJdIAIKiOaC+k6aQkKBPEVzf+sz6piCGMNzfej4tsww=,tag:GNBaStFJc2XaoM5x5WgxDg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:MQdJi1ZfJKdJ0Q5vhrFHvX79s1t9gYsv0omHcQa1qtrj1wjsDAeI9b5t6LA=,iv:g7rdmzM7tVguxho9vvI+s0iJyOjdwG2tTXg1KCqyoc0=,tag:JGCMCj13JbMH9Dx6ty4YHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZVNnMzJGdjU0dTVGQktB
            dGpnQ2x5M3lra2RKbHcyMm5zdTZueFlaeWt3CjlMbjA0bmh4R1BKTkZDdENzckxh
            UU1vOEZvNVdkSGZlaDdKM21WQU1YcE0KLS0tIGtnQlNlYlJ4c05CSmF0WGVDM3dB
            V09DWkJWcS96aUlBRE9sT1FNSVdPUk0Kb0UdEu1v49NMrfCBddOTcY2MGldQsNjD
            9R2/vAPzpJq3Q//dcDo3vjYdDbmTkYtB2DjFaI3WUDl8LAIaUPC3Qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T20:19:33Z"
    mac: ENC[AES256_GCM,data:CCKp2If5sG+VGba4VByfW61JJArRDnAMB4FCFGWmPTmBFqsS6iJBCbmg0fIsdpj6rTKiFBNn1dAlhggSWDaclD12Zjh8SltrRFevCExTohjWV1/7LcpwWglWCjd8EIqL4x0IW6V4gxLutCFHuTaICv/ujzfi7nfkwR53KeVPNyQ=,iv:DW+4JMDF9jCu7BnOBeqzdvpvgwLkxkt3aRjCxPrypQU=,tag:MTeV+Ft0iVR5sPtxzu6j6Q==,type:str]
    version: 3.13.1
