apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backups
resources:
  - namespace.yaml
  - shared
  - mattermost
  - keycloak
  - nextcloud
  - firefly
  - bookstack
configMapGenerator:
  - name: mattermost-backup-scripts
    files:
      - shared/common.sh
      - mattermost/scripts/pgdump.sh
      - mattermost/scripts/mmctl-export.sh
  - name: keycloak-backup-scripts
    files:
      - shared/common.sh
      - keycloak/scripts/pgdump.sh
  - name: nextcloud-backup-scripts
    files:
      - shared/common.sh
      - nextcloud/scripts/backup.sh
  - name: firefly-backup-scripts
    files:
      - shared/common.sh
      - firefly/scripts/dbdump.sh
  - name: bookstack-backup-scripts
    files:
      - shared/common.sh
      - bookstack/scripts/backup.sh
generatorOptions:
  disableNameSuffixHash: true
