apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - shared
  - mattermost
configMapGenerator:
  - name: backup-scripts
    files:
      - shared/common.sh
      - mattermost/scripts/pgdump.sh
      - mattermost/scripts/mmctl-export.sh
generatorOptions:
  disableNameSuffixHash: true
