apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-alertmanager-ntfy.yaml
  - secret-alertmanager-ntfy.sops.yaml
  - deployment-alertmanager-ntfy.yaml
  - service-alertmanager-ntfy.yaml
  - prometheusrule-backups.yaml
  - prometheusrule-test-alert.yaml
