apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-ntfy-auth
  namespace: observability
type: Opaque
stringData:
  auth.yml: |
    ntfy:
      baseurl: "http://ntfy.ntfy.svc.cluster.local"
      auth:
        basic:
          username: "alertmanager-publisher"
          password: "teeenyTINYassWORD_200!"
      notification:
        topic: "homelab-alerts"
