apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-auth
    namespace: observability
type: Opaque
stringData:
    auth.yml: ENC[AES256_GCM,data:IkUY2vK4A0kE1guZxALsxIj4KkaTt4hmyWGpr3ZyvGFJmBWNsu7gK7kOO9hL02LL4EgQgudp20fWMxvmrDNaqo0pu/8aHBf/Vaw5LdXC+YXFXW7BcrFyoHcbWdt0kUkHIv8P3JznmP/WhuA9XfAW77ChVr7kLeFAG9aIsBoPTLQF8HY2nL5Fh2SbnZdW0Ww+/GAY7egFvasN8K5EYVn9avRaIWu6+gZMYlb7Tp4d3A6hg9GoH3CLS2HAOryo38tJ75vC3SUV9ozQKdpV,iv:ddAwQKJ6NRUOX/L5hbhkgo4pfcQFB4jhbEOK65Mlank=,tag:QzypOWksgcp39By6ZHyn/Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RW5yMWFNTWpNM1hSM3JF
            azQ1eWlUQzQ1ZmlSZHlBcTBKeW14eXdQeDNjCi9sU3Zpd0M0QVpvNURyQm90UGoy
            S3NTYlFMRi9EMGZqVDN5QjZFVXhsTjgKLS0tIC9mNEtPOUZ3aEpHTS84ZDVCeEFB
            bGhnN3NnaEl5ajhVd3ZkbEJGTnVmZlEK4lqh/oocS0Pffqt3DCll10ktV6Mr/5KI
            Xy2FDHHb+BktsRw4rHjaHQ9W5gX61utW/CCVbO0QRGg/ZSpyYZfo9g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T02:27:44Z"
    mac: ENC[AES256_GCM,data:JQIP8DAlN9Yx6JXJ0zp8WlSxCbO8u3zo6bNz/n7vcjBgIRtwxW883+xoTeE5ZGjWO+DZNY1LOFowy3WA9ELQfew7qv/MzLlWgPl+hIWgJjX3W94Wib3ELJS/T8/5J6lleOYd61e0EQum1wSUTrtKkOiFR5aExB4JPnspDRey7Yc=,iv:uVm9dLIZXiaiT8ORJYZuwTGd0qmBIDGYGkRyDIly65s=,tag:hyVy1DdE0b5aco02Cc1vSw==,type:str]
    version: 3.13.1
