apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-ntfy-auth
    namespace: observability
type: Opaque
stringData:
    auth.yml: ENC[AES256_GCM,data:rUtrb+qLGaAwnp1Kg8ldeXOiqdmSzAjKYVAo7lBieTXH0U95/TbzfckzgMbZFMW4ELCdWJD6N8zTkDYGN0obJ/CUoMyZyWm/X1HF0eUDA4ahT5vomQZHhtzs5N141JBr/hf8J+sGvmbGE286Wju+5FsRqYTUK0j6r1zMOKy27LKsmHZsPLXN35XrV5KMmn6nBA3VyHF9kbpHKHHAhqRPuY9NWjqNYPhPKQ6CuOkg5+u0OuPnSwGByk26Xy0GB0l8DLAUEMQ2OFBq,iv:9G5p8rjpTGV84ewyOOdq6zkuuHRdkbL/QEkXcCDuY4I=,tag:j2O5oNIBoKXKv6cwwrbXMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dkQweTJtL2JuUmRSS1Fw
            anl6T3d6MEFQV1NjWjJiRDQzZE9SSmQzYXprCkdsVVowR3g5dEprM3ZoME8rbXgx
            UDJGRHRURGxVUTBacjRRM1hCa0JpZ28KLS0tIFRPcjlMR1NiSW1UeEdNVUowRmpX
            UTlZa2JMalpjQnpCbk5ISDZ3YlFzVjAKWSamARZLiUTvlbEWM9LqRlUdo9jChWn5
            SbdnCBOA2QM57fSp2s2siJQurvF1LRAEevCsxMQnPgfMH2jkEiqbbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T02:18:10Z"
    mac: ENC[AES256_GCM,data:h7iLnkcvlik7pyocGtrSmji4m0xYJRNHtnBYkXwAgv3nZcTyPZhrjudHswt65A3IFdeN9v5uPumV0pyglGUdiVfCr2Ya3um/my7q3Kg7+gAc6ikhQ6W2R6hzvI+OWy6tVJy9vZ16dA9cIZffK57E+e/CNOL973LQ4x2cWRtvalU=,iv:2RKOC1dKVkYL8/7wdt9mz/hy5u+u7q/Kvma61nO83AA=,tag:3rkMuskoifvdmxkf9cR9ag==,type:str]
    version: 3.13.1
