apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-backup-config
  namespace: backups
data:
  BACKUP_ROOT: /backups/k3s
  KEYCLOAK_APP_NAME: keycloak
  KEYCLOAK_POSTGRES_HOST: postgres.keycloak.svc.cluster.local
  KEYCLOAK_POSTGRES_PORT: "5432"
  KEYCLOAK_POSTGRES_DB: keycloak
  KEYCLOAK_POSTGRES_USER: keycloak
  KEYCLOAK_PGDUMP_KEEP: "14"
