apiVersion: v1
kind: Secret
metadata:
    name: keycloak-backup-secrets
    namespace: backups
type: Opaque
stringData:
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:L0myDTmNQTyXp5U=,iv:L8A8m5TsB8P1XNXjuOjz/cxFZKmdAzgF+jhHei0mZWg=,tag:HWUwRQUdXVkas3TvGr1zPQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN0pkelpoaW11aGljUXJy
            cVFhR2NlYXU1MktDTk5GK0RSSmhrYzFqUVVVCkZWajZJdHdPVndFOWExR1dwMEN4
            N29yWUR4eS96c0NXaDMzK1JNeUlYZkEKLS0tIGRnTW92RGZIbDFjZmNYekdKOEQv
            aThmT3krcko4cnZQMkZPa0dQS05zQ3cKAe4r2WTuEFGh2I/W6DtG5HF4Z8DDcjSQ
            rjrB+g2xO5ollIT5wJk/t+relmpnzn9KZbvw9Y+F+iD51OjZl5Gp5g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T11:45:46Z"
    mac: ENC[AES256_GCM,data:lnwVDDv6h33vcrUbitVcGaYx2s1GqYMGsflRMk8RFoyoKgD3c+4C1ykYLmtDDg0E+bXPwGGfAX72mpRkMEmJX8puueQqAhbiLyt8dO9EC3qmxqPUjdpSdWdJNuUIGjFq/G1+WB5GIDDcCtPfrSlu2hPP8mfMFu2xa+yiIOUdBC4=,iv:r0EnsbNQy46+ZjeJ/9P58O7m5Q+VL2SUkwHLhzDDnRc=,tag:oI0kR/PjpH2LbFoffuoF+Q==,type:str]
    version: 3.13.0
