apiVersion: v1
kind: Secret
metadata:
    name: audiomuseai-postgres
    namespace: audiomuseai
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ov6cfjTNRVsb,iv:socN5qZdWi65aQLtXnkDePUI+4NOAFqMtdeEO/G9WQ0=,tag:tHIPPGp/gej3xD9VsKjAPQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:q2MwiJbXHQ7JexQd8U7vXlaOOB9ul1QE7wo23KAGbw9NaaM9ME8=,iv:I/xv4kwTnjSsaIF/uN1ZtcuT64LWyYtOkc4GSUShI3g=,tag:YxQb5lqSyVXF7RL+g1x3zg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Z/gOGwhW5vzuSaM=,iv:Kfc6Tc0mVYAwbjXZaHx6dFnemQFRd/4xIxPYeF8ruus=,tag:LcuIM4u672iEJPj3Ua7b8A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZHlVeFM1eDY1bENTTWt0
            dzBXb0paRWNDaXMyN2J3TXZkNDVGc3ROdzI4CnJMTVF3VlFOckhoT2JNSVJQeFpR
            N1FiMGlmWFdITmsycUQ1eGdLWlgyQU0KLS0tIHpMWTJSeks5Yk1aeGxwak9aZmt5
            UldyTm9rR2hucHkwRVlTUmgvNndpeDAKEmkNMfhg//mcAmayi4z/70KWpury2MU2
            yZaASWOXvf7jayb8dsL8GR4MBoJaSP44xJnWl8pp505m8zMVDKD94A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T19:28:31Z"
    mac: ENC[AES256_GCM,data:cvJdqlthkxHWG+IPhRt9NWXz3BhEZF/FdgLF9xP6TCU05P05xUyneBhQfUM/nuOkbLX2Z/s6TYByBxyf/hlRC3bTS3ddw4MEZFBGfwH2HhC45gcqUk9vjiISL93vpJUziXq5NbL8IL5h8DsXrjbkDLxIXKxIBVIuoeocrkOx+KQ=,iv:V0roJw07ug1eDSHE6C/xhY6EtiR7e9yiAv1xhknXELA=,tag:E/m9oAdpf2kP6H846xchZQ==,type:str]
    version: 3.13.1
