apiVersion: v1
kind: Secret
metadata:
    name: audiomuseai-oauth2-proxy
    namespace: audiomuseai
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:1JfqU19Qtcc=,iv:DUTK5evm1lTY3F175DNL0Ptu/aVjy86vIAHT3BIdnzw=,tag:1a8NcBe2u5xkdoL4ozuJeg==,type:str]
    client-secret: ENC[AES256_GCM,data:A2/JHw4VfLRLQPdAABlp/hobWDMdmifkGiekUUHWgkA=,iv:W042Iwulfk6J0HVl0lZiBkReAnd1sTEB8TfpJyiFudg=,tag:TwRhavtgh1XFbHBuGUeubw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:slbYIVZOSOw89XLIfEqL85Ina9neVftEgL1DnjY4HJEHb7QrfY6CCqfc1uA=,iv:cDoH4p2yTQ6iHQIYzm8z8gkNLLNA35vFVFrGJbwOSj4=,tag:ZjLZcM6+S/Z/JesdGR5fzA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONkk2b2lUWTNNMDRsTVdQ
            bDFHVHIrMnBtV1ViZHNlNm4zdVRNSEt2VkJJCnJFNHZvQWdyWlp4bDBnMEpWbTNV
            WCtSYnVBdkU5OWl3NVVtbmpNOWtnVmsKLS0tIExTc3hSQk10cFE0cC81SXBReFh2
            VUhSTWE5aGdUWlVzZTg1Z3dXaksrZjAKyXiSB82LaY+sb6QCFktkmBcVYerxZyIL
            akzXgwBRENHDI7GbNy4wiiR9jsV+PuzzP6Sy2gDzC3IZdiT05hxOjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T19:57:22Z"
    mac: ENC[AES256_GCM,data:VL2KIBGMk9XNGGg0S4LucIYJvyrbS06MfdYliXf+if871TXBY8teQWcZW4CZIE0sKfI+M0QQdB9XIWjnI6ELsafaqvshxOxsvzzYQvk2VTGVjt2Mfy1OOKc9PDaYp6InWWNYrZDn9RfqsdF/AdXGm5Q/P3TCOQq6IvaHP3300WY=,iv:/VM6i093Fw8tnmDJiTG8iaf+k0NVDTdAnayu2c9VSQI=,tag:81HbpkkMg1I8DnYuBprfeA==,type:str]
    version: 3.13.1
