apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secrets
    namespace: keycloak
    labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/component: app
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:tv0bMDHw1+p39kM=,iv:r84d2DGpg5CyjjaMJKR0+rqluEmyUeZCVJwJ8//SCL8=,tag:+DOQyWEF/KpRWCdiGpUWbg==,type:str]
    KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:CsfIQYzHI9iKEPg=,iv:W5c7D+NIkKXRJ2lC8QNiNr7vdtBld9NNesKrk5Rim2c=,tag:sNQTKW20hlbDnx+JxeJ1IQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bjFUMTVlNjBGcXhHaWU5
            WlZiTkpzalBEL3k4K1pUV2o3VENhVlVrc0FjCndkRUlURkZrb3E5V1BMWjhsMzdI
            Q25GQ08xL2t6dXhZbmpQWFFFeWJqWXMKLS0tIHhZOGRFVVZ0Z3FzSkd4NURVK0N6
            UlhZbFpxRzJpSE4rSFFZZjNQd01NZW8K6T+JymyD4vSajodTZzBbXALnW+f35h72
            63S0Iyu77Tsm2YweG6k8Kn6f+UQm6zDLjhejx7COG/ei+KiPZZmfNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-10T14:42:47Z"
    mac: ENC[AES256_GCM,data:uMnlCexYHrvS2AcqfxvwcZIFazWj9wlbPeNsxjNgOlaLKkpdi/X1EwzDC7brkqI5po1g3+mKM7HW7RGwLYp02gkURjnWnOsltACWacebRZBaFv58xlT48BVtaaKRHw3ZlxOY96cW8t2lXDiAueWKnkyNRzeWx68eLFlIE6JQ7Go=,iv:eljbmuFqmodgh0+/OF/STQrJoc2s2/EbMiLOJMArNLI=,tag:T4hGSGXVzLFA5cgbSSIUYA==,type:str]
    version: 3.13.0
