apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nas-common
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k3s/cluster/apps/nas-attached/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m0s
