apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - kustomization-audiobookshelf.yaml
  - kustomization-calibre.yaml
  - kustomization-infra.yaml
  - kustomization-metallb-config.yaml
  - kustomization-cert-manager-config.yaml
  - kustomization-traefik-config.yaml
  - kustomization-secrets.yaml
  - kustomization-apps-replicated.yaml
  - kustomization-bookstack.yaml
  - kustomization-nas-common.yaml
  - kustomization-music-ingest.yaml
  - kustomization-navidrome.yaml
  - kustomization-picard.yaml
