apiVersion: v1
kind: Secret
metadata:
    name: step-issuer-provisioner-password
    namespace: step-issuer-system
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:DWGqprNnB220eJ6tH7fTMeAAWHHHAkj857BClEK4fbGjgGxhzNUPLM/TKZNNja74tefw5sXu0cRapCnK,iv:Y+d4WC73jkZa22KJiRNG+bLJHe43Z4W8nEbdwwFUTAY=,tag:duhbkTvXxQxGOyJvm99UHA==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUzRTVWk3V3dsSzIyWEYv
            ZGRBYW94c3NuQWY1YkttYjNKTUVEYStoVVJFCkljbG9QZTdLOVFUa1ljNlhoeHEv
            NGFRV3RDYzhHSUluZmRSbkJDRTlkTXMKLS0tIDAxR3NFVUpmbDJlbkJ3UjVpM2xa
            SXNONUZyVUNnN3laTk1PL1hmaFhTbmMKaBK3CFu6Mk3PBNQbopWOfjKzgQgiAjdp
            99oVTeGeKj0gt56E6sKN2HmkNe4VUSFA+jprx/jyMN3MgQIkFtsRlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T20:42:08Z"
    mac: ENC[AES256_GCM,data:eY1vYkMdAw4vHfutgd1aGICSupH/hp4E1yhzls2G2z9zEeP0JTVshIEtvfOqWvbcrJ6cmDkJT1bjj52FFXIb3g9p/FXUv0u4c3ClsLWhJI3GD8a9iQPJyMD2St/3Zx65c2yp9AO0rFZNZYDR753ddg1gMGExfdQ9ljvkif7BOHo=,iv:8Vqj/Mn+VcXF9mOQHo1Lkm+DxnYUQvEvRXx2GUQhMt4=,tag:zjnBrWAk4jIE0mmyRCW0dQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
