apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Y2Y8BnnRV3+9Gx1/HZR5kHeE1oSDfJbLFGLAYUDgb1EAd1zA3kMfuEAA4C5HXDPaLusztJTN+3e5frkN,iv:8Zq5YKR8paSKm467x4ciaubsH41kkNFXPXjM7+UFe1I=,tag:Ps2AjWkExiUMy+XnscfNaw==,type:str]
kind: Secret
metadata:
    name: step-issuer-provisioner-password
    namespace: step-issuer-system
type: Opaque
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzT1pzd0hoQnFYTGR4cmIy
            aGJSK0Irb1hBSUx1Zmt0TDBjZHJFSzNjS1dFCmJ0Mk9DTzZCNHU3a25teFI5OSt2
            QlpBYVA4RWNtclBVKzUwNWhuRDBKRXMKLS0tIDBHUzh4OXZVd1NTaU1NdVpoVkdz
            ZFVVSzlGbkVPTm5MSFdwZ2loZloxWEkKLx5wSgy65jX2/TVlOVO7KtHCHSmVu7tb
            2PJ1bUZMEwiVhEhYqsgBOdaPql0CMEoiFsRZcBJ/EUBusxraORSJzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T20:30:36Z"
    mac: ENC[AES256_GCM,data:3HkwIhQGnOxS7La2/45/1WZzYiWCtD/D7JVXfx/scJoc5DCOZZjLY7aVnxH9QhUwM/iHyD6w800NFm6ntNN/JdD6AHdOIGsZICAZ2Z50EBQNLBgzuTLG54SxGS5kTYbZUtB6gydZhoU9Edd2IsJaU69uhZ5Cz0LZdubpyMlR2Eg=,iv:CXtHgucOf+EIID9YEltzxd2ItSS3IO7fcnq3Oc80Su4=,tag:i8OAiEr5uqnUyTu9c0C6Wg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
