apiVersion: v1
data:
    password: ENC[AES256_GCM,data:q8AwMjlRP0yJRRviEIrVcjFp2jU30enGjdNdBvQIfdmtv30ZTpfmiE3VaE/F3MyT8PFobwlBUsW86o1U,iv:CLBs0q/d48D6qdwkHrN2wJaSrM+PGK4BDjrHNkO21+g=,tag:iMF8jxSuJL61yBq6dZhcYA==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2026-03-30T20:13:11Z"
    name: step-issuer-provisioner-password
    namespace: step-issuer-system
    resourceVersion: "3589316"
    uid: b2cd98d5-5d4f-4b1e-9546-1ca6b0c64eb2
type: Opaque
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1L0FpS2U0MklqZ1FmbHlT
            SEJzZm5OQktxUHRWK2cyQUk4WE1Wci9YTDJnCm5WRzZjVERGZTl3ei9wSmdmeEN2
            V0FQL3RqRFZzbWZTNm15SlhuT3FiWjAKLS0tIER5Y2JBK3kzMkxvN3QySWtzK0s0
            emtBZk9wUjVHT3RnR1pMdElocTkycXMKOEecrcNYBMAesbba6bGjE9aGRa+W9sik
            rvRAE40JpwVo3a29ZN6XDNZ3rpZFA9dB/iltl+gpRLjmjm62djZf2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T20:14:44Z"
    mac: ENC[AES256_GCM,data:jmppZTG48kwOQlOuXQH6V3HWxfOVs+igBKN0xfZ26MVyry8DzhEPTQOVz1OxNW2ivKgCDfg/NTck3llAcB/gnPafTlA9gsmI2bTDHPoqIg4DTUMfd9Y0OFrtz6UbS/ZQoRGl0uy7Kjes5lj2fdI5Q0AU8ZutTVqT7n3zeEu7bmY=,iv:MuirEZHUPBO6L5z3UGGsqaIoUEvIlJbOymLwPu7SZvM=,tag:kweZWd4UNNneNTTkZngAMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
