apiVersion: v1
kind: Secret
metadata:
    name: example-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:H8LFOE6e5Tn4,iv:cSm4+6qWBt3FhhOspCmwOMOwZDczpfMNuGAuMO2qgZU=,tag:pprO++emwTEKX5CSGlv0fA==,type:str]
    password: ENC[AES256_GCM,data:ePHGQSpfnhsSbMsJEQ==,iv:1nFWAMf05vY+BB7kWArWefOrtm25bOgy3Rg5WLsdCXk=,tag:NgOZ8fU9Tw2v6IBHeDNIUg==,type:str]
sops:
    age:
        - recipient: age1ctpyzt2xz3wralwgma6ctpnkztjpzsqvarjpayppmtpml2x4agaswc2j5y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqV0Z3cWZLZkpWYVNoNzlF
            dnA3b0drTVQ1MjFkTTNNMHNDamxCdHU4RmowCkdON0xlME05Y1BNc2RKM21zY0NN
            ZmM5cmpZS3lEMStVV0Z1MGZ5alBMZTAKLS0tIFZ5SEN1b3NTcXlnbEw3cXhJMTl6
            Ylc1T0NHMXRrRFRUNWd0SXg0NFJTS1UKnwEwU7ZQCbZ2vaQLp64byvIJbFkhqtbO
            ESXUEGcbDzp90B3MRFemsC/466Wm8mUIWiWa1Mr58VvwhoSH31hTGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T18:06:05Z"
    mac: ENC[AES256_GCM,data:PFR2x/DbxLU5+zbQG2+88SI/wcrH2buOvarH640TykQXODRusixhhDL1tQWhvjFIqDwNLNUSdsF3Q5H+Rq/P9+awJkDDj+98mYt/tV7nwS+eLgCwItIfX9QZUHKxzgnjJP7mjRrFrItUMCn4fCJ4KCliToxP2FZKGSsqWoqvPTY=,iv:r3NX3BJFju1LgMPYCDODWyS171RDw4xUmcMiZ+NCboA=,tag:sQAeZJMh6pXYhpHnbT2n7A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
