apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - secret.sops.yaml
  - serverstransport.yaml
  - service-mariadb.yaml
  - service-redis.yaml
  - service-nextcloud.yaml
  - statefulset-mariadb.yaml
  - deployment-redis.yaml
  - deployment-nextcloud.yaml
  - ingress.yaml
