apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
  labels:
    app.kubernetes.io/part-of: nextcloud
    app.kubernetes.io/name: nextcloud
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_PASSWORD: ""
