apiVersion: v1
kind: Pod
metadata:
  name: home-assistant-copy-config
  namespace: home-assistant
spec:
  restartPolicy: Never
  nodeSelector:
    longhorn: "enabled"
  containers:
    - name: shell
      image: alpine:3.22
      command: ["/bin/sh", "-c", "sleep infinity"]
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumeMounts:
        - name: source-homeassistant
          mountPath: /source/homeassistant
          readOnly: true
        - name: source-mosquitto
          mountPath: /source/mosquitto
          readOnly: true
        - name: source-mqtt-explorer
          mountPath: /source/mqtt-explorer
          readOnly: true
        - name: target-homeassistant
          mountPath: /target/homeassistant
        - name: target-mosquitto
          mountPath: /target/mosquitto
        - name: target-mqtt-explorer
          mountPath: /target/mqtt-explorer
  volumes:
    - name: source-homeassistant
      nfs:
        server: 192.168.1.231
        path: /mnt/user/appdata/homeassistant
    - name: source-mosquitto
      nfs:
        server: 192.168.1.231
        path: /mnt/user/appdata/mosquitto
    - name: source-mqtt-explorer
      nfs:
        server: 192.168.1.231
        path: /mnt/user/appdata/mqtt-explorer
    - name: target-homeassistant
      persistentVolumeClaim:
        claimName: homeassistant-config
    - name: target-mosquitto
      persistentVolumeClaim:
        claimName: mosquitto-config
    - name: target-mqtt-explorer
      persistentVolumeClaim:
        claimName: mqtt-explorer-config
